# Generated by Django 5.0.7 on 2025-10-08 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_photos/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
            },
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "candidate_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="candidate_photos/"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("education", models.JSONField(blank=True, null=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.candidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Profile",
                "verbose_name_plural": "Candidate Profiles",
                "indexes": [
                    models.Index(
                        fields=["candidate"], name="profiles_ca_candida_3f24dc_idx"
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="profiles_ca_first_n_b5739a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="recruiter_photos/"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Middle", "Middle"),
                            ("Senior", "Senior"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.recruiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruiter Profile",
                "verbose_name_plural": "Recruiter Profiles",
                "indexes": [
                    models.Index(
                        fields=["recruiter"], name="profiles_re_recruit_f4a0d0_idx"
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="profiles_re_first_n_a5b791_idx",
                    ),
                    models.Index(fields=["level"], name="profiles_re_level_99fa33_idx"),
                ],
            },
        ),
    ]
