# Generated by Django 5.0.7 on 2025-10-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecruiterProfile",
        ),
    ]
