# Generated by Django 5.0.7 on 2025-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_remove_recruiterprofile_authenticat_first_n_4166ca_idx_and_more",
        ),
        ("profiles", "0002_delete_recruiterprofile"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="candidateprofile",
            name="profiles_ca_first_n_b5739a_idx",
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="full_name",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["full_name"], name="profiles_ca_full_na_48772a_idx"
            ),
        ),
    ]
