# Generated by Django 5.0.7 on 2025-10-16 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_remove_candidateprofile_profiles_ca_first_n_b5739a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a company logo or photo (jpg, jpeg, png formats).",
                null=True,
                upload_to="company_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
