# Generated by Django 5.0.7 on 2025-10-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_recruiter_is_waiting_approval"),
        ("profiles", "0004_alter_companyprofile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companyprofile",
                to="authentication.company",
            ),
        ),
    ]
