# Generated by Django 5.0.7 on 2025-10-29 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_delete_recruiterprofile"),
        ("profiles", "0005_alter_companyprofile_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the recruiter profile.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Full name of the recruiter.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number of the recruiter.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Profile photo of the recruiter.",
                        null=True,
                        upload_to="recruiter_photos/",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Recruiter", "Recruiter"),
                            ("Manager", "Manager"),
                            ("Admin", "Admin"),
                        ],
                        default="Recruiter",
                        help_text="Access level of the recruiter (Recruiter, Manager, Admin).",
                        max_length=20,
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="Reference to the recruiter user account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.recruiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruiter Profile",
                "verbose_name_plural": "Recruiter Profiles",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["recruiter"], name="profiles_re_recruit_f4a0d0_idx"
                    ),
                    models.Index(
                        fields=["full_name"], name="profiles_re_full_na_0c2071_idx"
                    ),
                    models.Index(fields=["level"], name="profiles_re_level_99fa33_idx"),
                ],
            },
        ),
    ]
