# Generated by Django 5.0.7 on 2025-11-22 12:17

import utils.fields.uuid7_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_recruiterprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="id",
            field=utils.fields.uuid7_field.UUIDField(
                default=utils.fields.uuid7_field.uuidv7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
