# Generated by Django 5.0.7 on 2025-11-22 14:04

import utils.fields.uuid7_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_candidateprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="id",
            field=utils.fields.uuid7_field.UUIDField(
                default=utils.fields.uuid7_field.uuidv7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="id",
            field=utils.fields.uuid7_field.UUIDField(
                default=utils.fields.uuid7_field.uuidv7,
                editable=False,
                help_text="Unique identifier for the recruiter profile.",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
