# Generated by Django 5.0.7 on 2025-12-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_remove_company_type_field"),
        ("profiles", "0008_alter_companyprofile_id_alter_recruiterprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="address",
            field=models.CharField(
                choices=[
                    ("Andijon", "Andijon"),
                    ("Buxoro", "Buxoro"),
                    ("Jizzax", "Jizzax"),
                    ("Qashqadaryo", "Qashqadaryo"),
                    ("Navoiy", "Navoiy"),
                    ("Namangan", "Namangan"),
                    ("Samarqand", "Samarqand"),
                    ("Sirdaryo", "Sirdaryo"),
                    ("Surxondaryo", "Surxondaryo"),
                    ("Toshkent shahar", "Toshkent shahar"),
                    ("Toshkent viloyati", "Toshkent viloyati"),
                    ("Farg'ona", "Farg'ona"),
                    ("Xorazm", "Xorazm"),
                ],
                default="Toshkent shahar",
                help_text="Choice of region in Uzbekistan",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["company"], name="profiles_co_company_b63333_idx"
            ),
        ),
    ]
