# Generated by Django 5.0.7 on 2025-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_candidateprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="region",
            field=models.CharField(
                choices=[
                    ("Andijon", "Andijon"),
                    ("Buxoro", "Buxoro"),
                    ("Jizzax", "Jizzax"),
                    ("Qashqadaryo", "Qashqadaryo"),
                    ("Navoiy", "Navoiy"),
                    ("Namangan", "Namangan"),
                    ("Samarqand", "Samarqand"),
                    ("Sirdaryo", "Sirdaryo"),
                    ("Surxondaryo", "Surxondaryo"),
                    ("Toshkent shahar", "Toshkent shahar"),
                    ("Toshkent viloyati", "Toshkent viloyati"),
                    ("Farg'ona", "Farg'ona"),
                    ("Xorazm", "Xorazm"),
                ],
                default="Toshkent shahar",
                help_text="Region in Uzbekistan",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Full address of the candidate",
                max_length=255,
                null=True,
            ),
        ),
    ]
