# Generated by Django migration
from django.db import migrations, models


def migrate_manager_to_admin(apps, schema_editor):
    """
    Migrate all recruiters with Manager level to Admin level.
    Since Manager level is being removed, we promote them to Admin.
    """
    RecruiterProfile = apps.get_model('profiles', 'RecruiterProfile')
    updated_count = RecruiterProfile.objects.filter(level='Manager').update(level='Admin')



def reverse_migration(apps, schema_editor):
    """
    Reverse migration is a no-op since we can't know which Admins 
    were previously Managers.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_companyprofile_created_at_companyprofile_updated_at'),
    ]

    operations = [
        # First, migrate existing Manager data to Admin
        migrations.RunPython(migrate_manager_to_admin, reverse_migration),
        
        # Then, update the field choices to remove Manager
        migrations.AlterField(
            model_name='recruiterprofile',
            name='level',
            field=models.CharField(
                choices=[('Recruiter', 'Recruiter'), ('Admin', 'Admin')],
                default='Recruiter',
                help_text='Access level of the recruiter (Recruiter or Admin).',
                max_length=20,
            ),
        ),
    ]
