# Generated by Django 5.0.7 on 2026-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_companyprofile_latitude_companyprofile_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
    ]
