# Generated by Django 5.1.15 on 2026-03-09 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_alter_companyprofile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="Enter a website URL or domain (http/https optional).",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_website",
                        message="Enter a valid website URL or domain (http/https optional).",
                        regex="^(https?://)?([a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})(:[0-9]{1,5})?(/.*)?$",
                    )
                ],
            ),
        ),
    ]
