# Generated by Django 5.1.15 on 2026-03-23 09:20

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_alter_companyprofile_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citizenship",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the citizenship/country",
                        max_length=100,
                        verbose_name="Citizenship name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        help_text="Name of the citizenship/country",
                        max_length=100,
                        null=True,
                        verbose_name="Citizenship name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the citizenship/country",
                        max_length=100,
                        null=True,
                        verbose_name="Citizenship name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Name of the citizenship/country",
                        max_length=100,
                        null=True,
                        verbose_name="Citizenship name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Citizenship",
                "verbose_name_plural": "Citizenships",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Candidate's date of birth (format: YYYY-MM-DD)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="citizenship",
            field=models.ForeignKey(
                blank=True,
                help_text="Candidate's citizenship",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_profiles",
                to="profiles.citizenship",
            ),
        ),
    ]
