# Generated by Django 5.1.15 on 2026-03-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_add_citizenship_and_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateprofile",
            name="date_of_birth",
        ),
    ]
