# Generated by Django 5.1.15 on 2026-05-01 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_remove_date_of_birth_from_candidateprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="github_url",
            field=models.CharField(
                blank=True,
                help_text="GitHub profile URL (e.g., github.com/username).",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_github_url",
                        message="Enter a valid GitHub profile URL (e.g., github.com/username).",
                        regex="^(https?://)?github\\.com/[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?/?$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="linkedin_url",
            field=models.CharField(
                blank=True,
                help_text="LinkedIn profile URL (e.g., linkedin.com/in/username).",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_linkedin_url",
                        message="Enter a valid LinkedIn profile URL (e.g., linkedin.com/in/username).",
                        regex="^(https?://)?(www\\.)?linkedin\\.com/(in|company)/[a-zA-Z0-9\\-%]+/?$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="social_url",
            field=models.CharField(
                blank=True,
                help_text="Portfolio or personal website URL.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_social_url",
                        message="Enter a valid portfolio or personal website URL.",
                        regex="^(https?://)?([a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})(:[0-9]{1,5})?(/.*)?$",
                    )
                ],
            ),
        ),
    ]
