# Generated by Django 5.1.15 on 2026-05-02 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_add_url_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="telegram_url",
            field=models.CharField(
                blank=True,
                help_text="Telegram username or link (e.g., t.me/username or @username).",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_telegram_url",
                        message="Enter a valid Telegram username (e.g., t.me/username or @username).",
                        regex="^((https?://)?(www\\.)?t\\.me/|@)?[a-zA-Z][a-zA-Z0-9_]{4,31}$",
                    )
                ],
            ),
        ),
    ]
