# Generated by Django 5.1.15 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_candidateprofile_telegram_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
