# Generated by Django 5.1.15 on 2026-05-15 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_companyprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="telegram_url",
            field=models.CharField(
                blank=True,
                help_text="Telegram profile URL (e.g., https://t.me/username).",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_telegram_url",
                        message="Enter a valid Telegram URL (e.g., https://t.me/username).",
                        regex="^https://t\\.me/[a-zA-Z][a-zA-Z0-9_]{4,31}$",
                    )
                ],
            ),
        ),
    ]
