# Generated by Django 5.1.15 on 2026-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0023_alter_candidateprofile_telegram_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="brand_accent_color",
            field=models.CharField(
                blank=True, help_text="Hex color for accents", max_length=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="brand_border_color",
            field=models.CharField(
                blank=True, help_text="Hex color for borders", max_length=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="brand_color_from",
            field=models.CharField(
                blank=True, help_text="Hex color e.g. #F8EDD9", max_length=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="brand_color_to",
            field=models.CharField(
                blank=True, help_text="Hex color e.g. #FCE8DA", max_length=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="brand_font",
            field=models.CharField(
                blank=True,
                help_text="Google Font name e.g. Caveat",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="brand_text_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color for text on brand bg",
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="tagline",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
