# Generated by Django 5.1.15 on 2026-06-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0031_companyprofile_brand_name_image_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companygalleryimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="companygalleryimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
