from django.db.models import Prefetch
from pgvector.django import CosineDistance
from apps.profiles.models import CompanyProfile


class VacancyMatcher:
    """
    Match resumes to vacancies using vector similarity with pgvector.

    This service assumes embeddings are already stored in the database
    (generated by the external embedding service and stored via Redis queue).
    """

    @staticmethod
    def find_matching_resumes(vacancy, top_k=30, min_similarity=0.3):
        """
        Find resumes that match a given vacancy using vector similarity.

        Args:
            vacancy: Vacancy instance (must have embedding generated)
            top_k: Maximum number of results
            min_similarity: Minimum similarity score (0-1)

        Returns:
            List of Resume objects with similarity_score attribute

        How it works:
        1. Uses pgvector's CosineDistance for similarity search
        2. CosineDistance(embedding, vacancy.embedding) returns distance (0-2)
        3. Convert distance to similarity: similarity = 1 - distance
        4. Filter by min_similarity threshold
        """
        from apps.resumes.models import Resume

        if vacancy.embedding is None or not vacancy.is_embedded:
            raise ValueError(
                "Vacancy has no embedding. Wait for background task to complete."
            )

        # Find similar resumes using cosine distance
        # Use select_related and prefetch_related to prevent N+1 queries
        # when serializing results through ResumeSerializer.
        matching_resumes = (
            Resume.objects.annotate(
                distance=CosineDistance("embedding", vacancy.embedding)
            )
            .filter(embedding__isnull=False, is_embedded=True)
            .select_related(
                "candidate",
                "candidate__candidateprofile",
                "domain",
            )
            .prefetch_related(
                "resume_skills__skill",
                "experiences",
                "certificates",
                "language_certificates__language",
            )
            .order_by("distance")[:top_k]
        )

        # Convert distance to similarity and filter
        results = []
        for resume in matching_resumes:
            similarity = 1 - resume.distance
            if similarity >= min_similarity:
                resume.similarity_score = similarity
                results.append(resume)

        return results

    @staticmethod
    def find_matching_vacancies(resume, top_k=10, min_similarity=0.3):
        """
        Find vacancies that match a given resume using vector similarity.

        Args:
            resume: Resume instance (must have embedding generated)
            top_k: Maximum number of results
            min_similarity: Minimum similarity score (0-1)

        Returns:
            List of Vacancy objects with similarity_score attribute
        """
        from apps.vacancies.models import Vacancy

        if resume.embedding is None or not resume.is_embedded:
            raise ValueError(
                "Resume has no embedding. Wait for background task to complete."
            )

        # Find similar vacancies
        # Use select_related and prefetch_related to prevent N+1 queries
        # when serializing results through VacancySerializer.
        matching_vacancies = (
            Vacancy.objects.annotate(
                distance=CosineDistance("embedding", resume.embedding)
            )
            .filter(
                embedding__isnull=False,
                is_embedded=True,
                is_active=True,
            )
            .select_related("company", "created_by", "domain")
            .prefetch_related(
                "vacancyskill_set__skill",
                "vacancy_languages__language",
                Prefetch(
                    "company__companyprofile",
                    queryset=CompanyProfile.objects.only(
                        "id", "company_id", "photo", "employees_count", "address", "latitude", "longitude"
                    ),
                ),
            )
            .order_by("distance")[:top_k]
        )

        # Convert distance to similarity and filter
        results = []
        for vacancy in matching_vacancies:
            similarity = 1 - vacancy.distance
            if similarity >= min_similarity:
                vacancy.similarity_score = similarity
                results.append(vacancy)

        return results
