# Generated by Django 5.0.7 on 2025-10-08 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EduPartnersType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Educational Partner Type",
                "verbose_name_plural": "Educational Partner Types",
            },
        ),
        migrations.CreateModel(
            name="EduPartner",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="edupartner_logos/")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edupartner_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="edupartners.edupartnerstype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
