# Generated by Django 5.0.7 on 2025-11-13 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_hrcreatedprofession"),
        ("edupartners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edupartner",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the faculty (e.g., Computer Science, Business)",
                        max_length=255,
                        verbose_name="Faculty Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the faculty",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the faculty is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="The domain associated with this faculty",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculties",
                        to="domain.domain",
                        verbose_name="Domain",
                    ),
                ),
                (
                    "edupartner",
                    models.ForeignKey(
                        help_text="The educational partner this faculty belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculties",
                        to="edupartners.edupartner",
                        verbose_name="Educational Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
                "ordering": ["name"],
            },
        ),
    ]
