# Generated by Django 5.0.7 on 2025-11-14 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edupartners", "0002_alter_edupartner_id_faculty"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edupartner",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the subject (e.g., Data Structures, Marketing)",
                        max_length=255,
                        verbose_name="Subject Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the subject",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the subject is active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "acquired_skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Skills that can be acquired by studying this subject",
                        related_name="subjects",
                        to="skills.skill",
                        verbose_name="Acquired Skills",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="The faculty this subject belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="edupartners.faculty",
                        verbose_name="Faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
    ]
