# Generated by Django 5.0.7 on 2025-11-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edupartners", "0003_alter_edupartner_id_alter_faculty_id_subject"),
        ("skills", "0001_initial"),
    ]

    operations = [
        # Step 1: Create the through model
        migrations.CreateModel(
            name="SubjectSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("UNDEFINED", "Undefined"),
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="UNDEFINED",
                        help_text="Expected proficiency level acquired after studying this subject",
                        max_length=20,
                        verbose_name="Proficiency Level",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_skills",
                        to="skills.skill",
                        verbose_name="Skill",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_skills",
                        to="edupartners.subject",
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Skill",
                "verbose_name_plural": "Subject Skills",
            },
        ),
        # Step 2: Remove the old M2M field (without through table)
        migrations.RemoveField(
            model_name="subject",
            name="acquired_skills",
        ),
        # Step 3: Add the M2M field back with the through table
        migrations.AddField(
            model_name="subject",
            name="acquired_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills that can be acquired by studying this subject",
                related_name="subjects",
                through="edupartners.SubjectSkill",
                to="skills.skill",
                verbose_name="Acquired Skills",
            ),
        ),
        # Step 4: Add uniqueness constraint
        migrations.AddConstraint(
            model_name="subjectskill",
            constraint=models.UniqueConstraint(
                fields=("subject", "skill"), name="unique_subject_skill"
            ),
        ),
    ]
