# Generated by Django 5.1.15 on 2026-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edupartners", "0005_alter_edupartner_id_alter_edupartnerstype_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edupartner",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Full address of the educational partner",
                max_length=500,
                verbose_name="Address",
            ),
        ),
        migrations.AddField(
            model_name="edupartner",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="edupartner",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="edupartner",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="edupartner",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="edupartner",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="edupartner",
            name="name_uz",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="edupartnerstype",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="edupartnerstype",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="edupartnerstype",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
