# Generated by Django 5.2.13 on 2026-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edupartners", "0006_add_translated_name_description_and_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edupartner",
            name="name",
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name="edupartner",
            name="name_en",
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="edupartner",
            name="name_ru",
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="edupartner",
            name="name_uz",
            field=models.CharField(max_length=350, null=True),
        ),
    ]
