# Generated by Django 5.2.13 on 2026-06-06 11:19

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0033_customuser_preferred_language"),
        ("resumes", "0025_resume_is_reviewed"),
        ("skills", "0003_learningmaterial_skilllearningmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAnswer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "selected_option_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Selected option ID for MC questions",
                        max_length=10,
                    ),
                ),
                (
                    "open_ended_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Candidate's text answer for open-ended questions",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "points_earned",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "ai_evaluation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI evaluation result for open-ended: {score, feedback, matched_keywords, missing_keywords}",
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Test Answer",
                "verbose_name_plural": "Test Answers",
                "ordering": ["attempt", "question__order"],
            },
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Question order within the test"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("OPEN_ENDED", "Open-ended"),
                        ],
                        default="MULTIPLE_CHOICE",
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField(help_text="The question text")),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of options for MC questions: [{id, text}, ...]",
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        default=dict,
                        help_text="Correct answer: {option_id} for MC, {keywords, rubric, sample_answer} for open-ended",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1, help_text="Points for this question"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sub-competency category",
                        max_length=100,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation of the correct answer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Question",
                "verbose_name_plural": "Test Questions",
                "ordering": ["test", "order"],
            },
        ),
        migrations.CreateModel(
            name="SkillTest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        default="INTERMEDIATE",
                        help_text="Target proficiency level for this test",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AI-generated test title",
                        max_length=255,
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        default=10, help_text="Time limit in minutes"
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of questions"
                    ),
                ),
                (
                    "passing_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=70.0,
                        help_text="Minimum score percentage to pass",
                        max_digits=5,
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        default="groq",
                        help_text="AI model used to generate this test",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Test",
                "verbose_name_plural": "Skill Tests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Final score percentage",
                        max_digits=5,
                    ),
                ),
                ("total_points", models.PositiveIntegerField(default=0)),
                (
                    "earned_points",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("passed", models.BooleanField(default=False)),
                (
                    "result_message",
                    models.TextField(
                        blank=True, default="", help_text="AI-generated result message"
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="AI-analyzed strengths: [{category, description}]",
                    ),
                ),
                (
                    "weaknesses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="AI-analyzed weaknesses: [{category, description}]",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to="authentication.customuser",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Attempt",
                "verbose_name_plural": "Test Attempts",
                "ordering": ["-started_at"],
            },
        ),
    ]
