# Generated by Django 5.2.13 on 2026-06-06 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill_tests", "0001_initial"),
        ("student_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="roadmap_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_attempts",
                to="student_analytics.roadmapitem",
            ),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="skill_tests.skilltest",
            ),
        ),
        migrations.AddField(
            model_name="testanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="skill_tests.testattempt",
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="skill_tests.skilltest",
            ),
        ),
        migrations.AddField(
            model_name="testanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="skill_tests.testquestion",
            ),
        ),
        migrations.AddIndex(
            model_name="skilltest",
            index=models.Index(
                fields=["skill", "target_level"], name="skill_tests_skill_i_a5ea93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["candidate", "test"], name="skill_tests_candida_fcfa69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["candidate", "status"], name="skill_tests_candida_5e3281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(
                fields=["test", "order"], name="skill_tests_test_id_d80551_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="testanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="unique_attempt_question_answer"
            ),
        ),
    ]
