# Generated by Django 5.1.15 on 2026-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_tests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="input_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="Total AI input tokens used for this attempt"
            ),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="output_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="Total AI output tokens used for this attempt"
            ),
        ),
    ]
