# Generated by Django 5.1.15 on 2026-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_tests", "0003_add_input_output_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltest",
            name="input_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="AI input tokens used for test generation"
            ),
        ),
        migrations.AddField(
            model_name="skilltest",
            name="output_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="AI output tokens used for test generation"
            ),
        ),
    ]
