# Generated by Django 5.1.15 on 2026-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_tests", "0004_skilltest_input_tokens_skilltest_output_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltest",
            name="thinking_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="AI thinking/reasoning tokens used for test generation",
            ),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="thinking_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total AI thinking/reasoning tokens used for this attempt",
            ),
        ),
    ]
