# Generated by Django 5.1.15 on 2026-06-16 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_tests", "0005_skilltest_thinking_tokens_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="skilltest",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                help_text="Candidate who generated this test",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
