# Generated by Django 5.0.7 on 2025-10-08 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                        ],
                        default="FULL_TIME",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=400, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vacancies",
                        to="authentication.recruiter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VacancySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("minimum_years", models.IntegerField(default=0)),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="skills.skill"
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "unique_together": {("vacancy", "skill")},
            },
        ),
        migrations.AddField(
            model_name="vacancy",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="vacancies",
                through="vacancies.VacancySkill",
                to="skills.skill",
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["company"], name="vacancies_v_company_8fb323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["created_by"], name="vacancies_v_created_2393d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["created_at"], name="vacancies_v_created_52d616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["employment_type"], name="vacancies_v_employm_6a03e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["is_active"], name="vacancies_v_is_acti_e300ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["location"], name="vacancies_v_locatio_2347aa_idx"
            ),
        ),
    ]
