# Generated by Django 5.0.7 on 2025-10-13 12:55

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="combined_text_en",
            field=models.TextField(
                blank=True,
                help_text="Combined English text used for embedding generation (title + description + etc)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="Vector embedding of combined_text_en",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="is_embedded",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether embedding has been generated",
            ),
        ),
    ]
