# Generated by Django 5.0.7 on 2025-10-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("skills", "0001_initial"),
        ("vacancies", "0003_add_vector_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["is_embedded", "created_at"],
                name="vacancies_v_is_embe_e5c1d3_idx",
            ),
        ),
    ]
