# Generated by Django 5.0.7 on 2025-10-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
        ("vacancies", "0004_vacancy_vacancies_v_is_embe_e5c1d3_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="description",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="about_us",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="additional_info",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="contact_email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vacancies",
                to="domain.domain",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="employment_format",
            field=models.CharField(
                choices=[
                    ("ON_SITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                default="ON_SITE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="responsibilities",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("UZS", "UZS"), ("EUR", "EUR")],
                default="UZS",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="combined_text_en",
            field=models.TextField(
                blank=True,
                help_text="Combined English text used for embedding generation (title + requirements + etc)",
                null=True,
            ),
        ),
    ]
