# Generated by Django 5.0.7 on 2025-10-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0005_remove_vacancy_description_vacancy_about_us_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="additional_info",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
