# Generated by Django 5.0.7 on 2025-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0006_alter_vacancy_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancyskill",
            name="minimum_years",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vacancyskill",
            name="proficiency_level",
            field=models.CharField(
                choices=[
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                    ("EXPERT", "Expert"),
                ],
                default="BEGINNER",
                max_length=20,
            ),
        ),
    ]
