# Generated by Django 5.0.7 on 2025-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0007_alter_vacancyskill_minimum_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancyskill",
            name="proficiency_level",
            field=models.CharField(
                choices=[
                    ("UNDEFINED", "Undefined"),
                    ("BEGINNER", "Beginner"),
                    ("INTERMEDIATE", "Intermediate"),
                    ("ADVANCED", "Advanced"),
                    ("EXPERT", "Expert"),
                ],
                default="UNDEFINED",
                max_length=20,
            ),
        ),
    ]
