# Generated by Django 5.0.7 on 2025-11-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0008_alter_vacancyskill_proficiency_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="number_of_positions",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of specialists HR wants to hire for this vacancy",
            ),
        ),
    ]
