# Generated by Django 5.0.7 on 2025-11-18 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_candidate_faculty"),
        ("vacancies", "0009_vacancy_number_of_positions"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyView",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_start", models.DateTimeField(auto_now_add=True)),
                ("session_end", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.candidate",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy View",
                "verbose_name_plural": "Vacancy Views",
                "indexes": [
                    models.Index(
                        fields=["vacancy"], name="vacancies_v_vacancy_7fd3e1_idx"
                    ),
                    models.Index(
                        fields=["candidate"], name="vacancies_v_candida_1020d0_idx"
                    ),
                    models.Index(
                        fields=["session_start"], name="vacancies_v_session_beb8f6_idx"
                    ),
                ],
            },
        ),
    ]
