# Generated by Django 5.0.7 on 2025-11-25 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0011_alter_vacancy_id_alter_vacancyview_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancyview",
            name="viewed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
