# Generated by Django 5.0.7 on 2026-02-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_userconsent"),
        ("vacancies", "0012_vacancyview_viewed_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vacancyview",
            unique_together={("vacancy", "candidate", "session_start")},
        ),
    ]
