# Generated by Django 5.0.7 on 2026-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0013_alter_vacancyview_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="expire",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=30,
                help_text="Expiration date for the vacancy",
                null=True,
            ),
        ),
    ]
