# Generated by Django 5.0.7 on 2026-02-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0014_vacancy_expire"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vacancy",
            name="vacancies_v_locatio_2347aa_idx",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="location",
        ),
    ]
