# Generated by Django 5.1.15 on 2026-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0015_remove_vacancy_vacancies_v_locatio_2347aa_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude for geospatial queries",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable location name (e.g., city, region)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude for geospatial queries",
                max_digits=9,
                null=True,
            ),
        ),
    ]
