# Generated by Django 5.1.15 on 2026-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0016_vacancy_latitude_vacancy_location_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Latitude for geospatial queries",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Longitude for geospatial queries",
                max_digits=30,
                null=True,
            ),
        ),
    ]
