# Generated by Django 5.1.15 on 2026-04-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0017_alter_vacancy_latitude_alter_vacancy_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="location_name",
            new_name="location",
        ),
    ]
