# Generated by Django 5.1.15 on 2026-04-10 00:00

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_alter_company_tin"),
        ("vacancies", "0018_rename_location_name_vacancy_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavouriteVacancy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_vacancy_entries",
                        to="authentication.candidate",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_vacancy_entries",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favourite Vacancy",
                "verbose_name_plural": "Favourite Vacancies",
                "indexes": [
                    models.Index(
                        fields=["candidate", "created_at"],
                        name="vacancies_f_candid_70af4a_idx",
                    ),
                    models.Index(
                        fields=["vacancy"],
                        name="vacancies_f_vacancy_cdfec2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "vacancy"),
                        name="unique_candidate_favourite_vacancy",
                    )
                ],
            },
        ),
    ]
