# Generated by Django 5.1.15 on 2026-04-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0019_favouritevacancy"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="favouritevacancy",
            new_name="vacancies_f_candida_1bcfe6_idx",
            old_name="vacancies_f_candid_70af4a_idx",
        ),
        migrations.RenameIndex(
            model_name="favouritevacancy",
            new_name="vacancies_f_vacancy_c32525_idx",
            old_name="vacancies_f_vacancy_cdfec2_idx",
        ),
    ]
