# Generated by Django 5.1.15 on 2026-04-18 08:06

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        (
            "vacancies",
            "0020_rename_vacancies_f_candid_70af4a_idx_vacancies_f_candida_1bcfe6_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyLanguage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        help_text="Required CEFR proficiency level (A1-C2)",
                        max_length=2,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Required language",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_requirements",
                        to="languages.language",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="Vacancy this language requirement belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_languages",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy Language",
                "verbose_name_plural": "Vacancy Languages",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vacancy", "language"), name="unique_vacancy_language"
                    )
                ],
            },
        ),
    ]
