# Generated by Django 5.1.15 on 2026-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0021_add_vacancy_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="minimum_ai_score",
            field=models.PositiveSmallIntegerField(
                default=40,
                help_text="Minimum AI evaluation score (0-100) for auto-acceptance. Applications below this threshold are auto-rejected.",
            ),
        ),
    ]
