# Generated by Django 5.1.15 on 2026-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0022_add_minimum_ai_score_to_vacancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="about_us",
            field=models.TextField(default="", max_length=10000),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="additional_info",
            field=models.TextField(blank=True, default="", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(default="", max_length=10000),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="responsibilities",
            field=models.TextField(default="", max_length=10000),
        ),
    ]
