# Generated by Django 5.1.15 on 2026-06-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0023_add_max_length_to_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If True, this vacancy is demo/placeholder data shown to unapproved companies.",
            ),
        ),
    ]
