# Generated by Django 5.0.7 on 2025-10-08 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=240, verbose_name="Position Title"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=240, null=True, verbose_name="Position Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=240, null=True, verbose_name="Position Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=240, null=True, verbose_name="Position Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the position.",
                        max_length=5000,
                        verbose_name="Position Description",
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the position.",
                        max_length=5000,
                        null=True,
                        verbose_name="Position Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the position.",
                        max_length=5000,
                        null=True,
                        verbose_name="Position Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="A brief description of the position.",
                        max_length=5000,
                        null=True,
                        verbose_name="Position Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "CareerOption",
                "verbose_name_plural": "CareerOptions",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Question Title"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Question Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Question Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Question Title"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Quiz title (e.g., 'Main Career Guidance Quiz')",
                        max_length=255,
                        verbose_name="Quiz Name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        help_text="Quiz title (e.g., 'Main Career Guidance Quiz')",
                        max_length=255,
                        null=True,
                        verbose_name="Quiz Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Quiz title (e.g., 'Main Career Guidance Quiz')",
                        max_length=255,
                        null=True,
                        verbose_name="Quiz Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Quiz title (e.g., 'Main Career Guidance Quiz')",
                        max_length=255,
                        null=True,
                        verbose_name="Quiz Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Quiz instructions/overview",
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True,
                        help_text="Quiz instructions/overview",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Quiz instructions/overview",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Quiz instructions/overview",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Publication status",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Type identifier (e.g., 'WORKXPLORER Career Guidance', 'Python Skill Assessment')",
                        max_length=100,
                        verbose_name="Quiz Type Name",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        help_text="Type identifier (e.g., 'WORKXPLORER Career Guidance', 'Python Skill Assessment')",
                        max_length=100,
                        null=True,
                        verbose_name="Quiz Type Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Type identifier (e.g., 'WORKXPLORER Career Guidance', 'Python Skill Assessment')",
                        max_length=100,
                        null=True,
                        verbose_name="Quiz Type Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Type identifier (e.g., 'WORKXPLORER Career Guidance', 'Python Skill Assessment')",
                        max_length=100,
                        null=True,
                        verbose_name="Quiz Type Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of quiz type purpose",
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uz",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of quiz type purpose",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of quiz type purpose",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of quiz type purpose",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Controls visibility of this quiz type",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Type",
                "verbose_name_plural": "Quiz Types",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500, verbose_name="Answer Text")),
                (
                    "text_uz",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Answer Text"
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Answer Text"
                    ),
                ),
                (
                    "text_ru",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Answer Text"
                    ),
                ),
                (
                    "point",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Points",
                    ),
                ),
                (
                    "career_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_choices",
                        to="quiz.careeroption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.question",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "AnswerChoice",
                "verbose_name_plural": "AnswerChoices",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
                verbose_name="Quiz",
            ),
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("career_options", models.JSONField(default=list)),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="The candidate who submitted the quiz result.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_results",
                        to="authentication.candidate",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="quiz.quiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Result",
                "verbose_name_plural": "Quiz Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="quiz_type",
            field=models.ForeignKey(
                help_text="Category classification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="quiz.quiztype",
                verbose_name="Quiz Type",
            ),
        ),
    ]
