# Generated by Django 5.0.7 on 2026-02-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_domain_description_en_domain_description_ru_and_more"),
        ("quiz", "0002_alter_answerchoice_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerchoice",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="The domain/field this answer corresponds to for domain determination",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answer_choices",
                to="domain.domain",
                verbose_name="Domain",
            ),
        ),
        migrations.AddField(
            model_name="quiztype",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="The domain/field this quiz type belongs to (e.g., IT, Healthcare)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz_types",
                to="domain.domain",
                verbose_name="Domain",
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="career_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_choices",
                to="quiz.careeroption",
            ),
        ),
    ]
