# Generated by Django 5.1.15 on 2026-03-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_domain_description_en_domain_description_ru_and_more"),
        ("quiz", "0003_answerchoice_domain_quiztype_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerchoice",
            name="domains",
            field=models.ManyToManyField(
                blank=True,
                help_text="The domains/fields this answer corresponds to for domain determination",
                related_name="answer_choices",
                to="domain.domain",
                verbose_name="Domains",
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Deprecated: Use 'domains' M2M field instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_answer_choices",
                to="domain.domain",
                verbose_name="Domain (Legacy)",
            ),
        ),
    ]
