# Generated by Django 5.1.15 on 2026-03-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_migrate_domain_fk_to_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answerchoice",
            name="domain",
        ),
    ]
