# Generated by Django 5.1.15 on 2026-03-10 10:46

from django.db import migrations, models


def copy_fk_to_m2m(apps, schema_editor):
    """Copy existing FK domain data to the new M2M domains field."""
    QuizType = apps.get_model("quiz", "QuizType")
    for qt in QuizType.objects.filter(domain__isnull=False):
        qt.domains.add(qt.domain)


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_domain_description_en_domain_description_ru_and_more"),
        ("quiz", "0006_remove_domain_fk_from_answerchoice"),
    ]

    operations = [
        # Step 1: Add M2M field
        migrations.AddField(
            model_name="quiztype",
            name="domains",
            field=models.ManyToManyField(
                blank=True,
                help_text="The domains/fields this quiz type belongs to (e.g., IT, Healthcare)",
                related_name="quiz_types",
                to="domain.domain",
                verbose_name="Domains",
            ),
        ),
        # Step 2: Copy FK data to M2M
        migrations.RunPython(copy_fk_to_m2m, migrations.RunPython.noop),
        # Step 3: Remove old FK field
        migrations.RemoveField(
            model_name="quiztype",
            name="domain",
        ),
    ]
