# Generated by Django 5.1.15 on 2026-04-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_convert_quiztype_domain_fk_to_m2m"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careeroption",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills relevant to this career option",
                related_name="career_options",
                to="skills.skill",
                verbose_name="Skills",
            ),
        ),
    ]
