# Generated by Django 5.1.15 on 2026-04-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_domain_description_en_domain_description_ru_and_more"),
        ("quiz", "0008_careeroption_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="The domain determined for this candidate from the quiz.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz_results",
                to="domain.domain",
            ),
        ),
    ]
