# Generated by Django 5.1.15 on 2026-04-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_customuser_preferred_language"),
        ("quiz", "0009_quizresult_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                help_text="The candidate who submitted the quiz result.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_results",
                to="authentication.candidate",
            ),
        ),
    ]
