# Generated by Django 5.0.7 on 2025-10-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_remove_resumeskill_combined_text_en_and_more"),
        ("resumes", "0004_add_vector_index"),
    ]

    operations = []
