# Generated by Django 5.0.7 on 2025-10-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("resumes", "0005_merge_20251013_1849"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["is_embedded", "created_at"],
                name="resumes_res_is_embe_0abf0e_idx",
            ),
        ),
    ]
