# Generated by Django 5.0.7 on 2025-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0007_alter_resumeskill_proficiency_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
    ]
