# Generated by Django 5.0.7 on 2025-11-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_hrcreatedprofession"),
        ("resumes", "0008_resume_updated_at_alter_resume_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Professional domain/field",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resumes",
                to="domain.domain",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="position",
            field=models.CharField(
                default="Software Developer",
                help_text="Desired job position/title",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("ACTIVELY_LOOKING", "Actively looking"),
                    ("OPEN_TO_OPPORTUNITIES", "Open to opportunities"),
                    ("NOT_LOOKING", "Not looking"),
                    ("EMPLOYED", "Currently employed"),
                ],
                default="ACTIVELY_LOOKING",
                help_text="Current work seeking status",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ResumeCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Certificate name", max_length=200),
                ),
                (
                    "issuing_organization",
                    models.CharField(
                        help_text="Organization that issued the certificate",
                        max_length=200,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        help_text="When the certificate was issued",
                        null=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, help_text="When the certificate expires", null=True
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True,
                        help_text="Certificate credential ID",
                        max_length=100,
                    ),
                ),
                (
                    "credential_url",
                    models.URLField(
                        blank=True, help_text="URL to verify the certificate"
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
    ]
