# Generated by Django 5.0.7 on 2025-11-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0009_alter_resume_id"),
        ("resumes", "0009_resume_domain_resume_position_resume_work_status_and_more"),
    ]

    operations = []
