# Generated by Django 5.0.7 on 2025-11-28 17:13

import apps.resumes.models.resume
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0010_merge_20251125_2235"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumecertificate",
            options={
                "ordering": ["-issue_date", "-created_at"],
                "verbose_name": "Resume Certificate",
                "verbose_name_plural": "Resume Certificates",
            },
        ),
        migrations.AddField(
            model_name="resumecertificate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resumecertificate",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Certificate file (jpg, jpeg, png, svg, zip - max 5MB)",
                null=True,
                upload_to=apps.resumes.models.resume.certificate_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "svg", "zip"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="resumecertificate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="resumecertificate",
            name="credential_id",
            field=models.CharField(
                blank=True,
                help_text="Certificate credential ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resumecertificate",
            name="credential_url",
            field=models.URLField(
                blank=True, help_text="URL to verify the certificate", null=True
            ),
        ),
        migrations.AlterField(
            model_name="resumecertificate",
            name="issuing_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization that issued the certificate",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resumecertificate",
            name="name",
            field=models.CharField(
                blank=True, help_text="Certificate name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="resumecertificate",
            name="resume",
            field=models.ForeignKey(
                help_text="Resume this certificate belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="resumes.resume",
            ),
        ),
    ]
