# Generated by Django 5.0.7 on 2025-11-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_merge_20251125_2235"),
        ("domain", "0002_hrcreatedprofession"),
        ("resumes", "0011_alter_resumecertificate_options_and_more"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="current_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to company if registered on platform",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employed_resumes",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="current_company_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the company where candidate is currently working",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="current_position",
            field=models.CharField(
                blank=True,
                help_text="Current job position/title",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="current_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current salary (optional, for analytics)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="employment_start_date",
            field=models.DateField(
                blank=True,
                help_text="Date when candidate started current job",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="salary_currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("UZS", "UZS"), ("EUR", "EUR")],
                default="UZS",
                help_text="Salary currency",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="combined_text_en",
            field=models.TextField(
                blank=True,
                help_text="Combined English text used for embedding generation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("ACTIVELY_LOOKING", "Actively looking"),
                    ("OPEN_TO_OPPORTUNITIES", "Open to opportunities"),
                    ("NOT_LOOKING", "Not looking"),
                    ("PART_TIME_CONSIDERING", "Considering part-time employment"),
                    ("EMPLOYED", "Employed"),
                    ("SELF_EMPLOYED", "Self Employed"),
                    ("FREELANCER", "Freelancer"),
                    ("INTERNSHIP", "Internship"),
                    ("STUDENT", "Student"),
                    ("UNEMPLOYED", "Unemployed"),
                ],
                default="ACTIVELY_LOOKING",
                help_text="Current work seeking status",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["work_status"], name="resumes_res_work_st_dbe901_idx"
            ),
        ),
    ]
