# Generated by Django 5.0.7 on 2025-11-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0010_merge_20251124_2349"),
        ("resumes", "0012_add_employment_fields"),
    ]

    operations = []
