# Generated by Django 5.0.7 on 2025-12-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0013_merge_20251129_1259"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeexperience",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="resumeexperience",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
