# Generated by Django 5.0.7 on 2025-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0014_resumeexperience_city_resumeexperience_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
    ]
