# Generated by Django 5.0.7 on 2025-12-14 17:20

import apps.resumes.models.resume
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_merge_20251129_1300"),
        ("domain", "0002_hrcreatedprofession"),
        ("resumes", "0015_alter_resume_title"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_main",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this is the candidate's main/primary resume",
            ),
        ),
        migrations.AlterField(
            model_name="resumecertificate",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Certificate file (max 5MB)",
                null=True,
                upload_to=apps.resumes.models.resume.certificate_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "svg", "zip", "pdf"]
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["candidate", "is_main"], name="resumes_res_candida_9e9882_idx"
            ),
        ),
    ]
