# Generated by Django 5.1.15 on 2026-02-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0016_resume_is_main_alter_resumecertificate_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumeexperience",
            name="years",
        ),
    ]
