# Generated by Django 5.1.15 on 2026-03-02 10:43

import apps.resumes.models.resume
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0001_initial"),
        ("resumes", "0017_remove_resumeexperience_years"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeLanguageCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                            ("B2", "B2 - Upper Intermediate"),
                            ("C1", "C1 - Advanced"),
                            ("C2", "C2 - Mastery"),
                        ],
                        help_text="CEFR proficiency level (A1-C2)",
                        max_length=2,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Certificate file proving proficiency (max 5MB)",
                        null=True,
                        upload_to=apps.resumes.models.resume.language_certificate_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "svg", "zip"]
                            )
                        ],
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        help_text="Language for this proficiency entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_certificates",
                        to="languages.language",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        help_text="Resume this language certificate belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_certificates",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Language Certificate",
                "verbose_name_plural": "Resume Language Certificates",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resume", "language"),
                        name="unique_resume_language_certificate",
                    )
                ],
            },
        ),
    ]
