# Generated by Django 5.1.15 on 2026-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0018_resumelanguagecertificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumelanguagecertificate",
            name="level",
            field=models.CharField(
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                help_text="CEFR proficiency level (A1-C2)",
                max_length=2,
            ),
        ),
    ]
