# Generated by Django 5.1.15 on 2026-03-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0020_add_pdf_to_language_certificate_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="salary_hide",
            field=models.BooleanField(
                default=False,
                help_text="Whether to hide salary from recruiters/HR views",
            ),
        ),
    ]
