# Generated by Django 5.1.15 on 2026-03-23 11:28

import apps.resumes.models.resume
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0021_add_salary_hide_to_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumelanguagecertificate",
            name="file",
            field=models.FileField(
                help_text="Certificate file proving proficiency (max 5MB, required)",
                null=True,
                upload_to=apps.resumes.models.resume.language_certificate_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "svg", "zip", "pdf"]
                    )
                ],
            ),
        ),
    ]
