# Generated by Django 5.1.15 on 2026-04-01 00:00

import apps.resumes.models.resume
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0022_alter_resumelanguagecertificate_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumelanguagecertificate",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional certificate file proving proficiency (max 5MB)",
                null=True,
                upload_to=apps.resumes.models.resume.language_certificate_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "svg", "zip", "pdf"]
                    )
                ],
            ),
        ),
    ]
