# Generated by Django 5.1.15 on 2026-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0024_add_created_by_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_reviewed",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True when the candidate has reviewed and accepted this resume. AI-generated resumes default to False until the candidate confirms them.",
            ),
        ),
    ]
