# Generated by Django 5.1.15 on 2026-06-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0025_resume_is_reviewed"),
        ("skill_tests", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeskill",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this skill has been verified via a skill test",
            ),
        ),
        migrations.AddField(
            model_name="resumeskill",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When the skill was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="resumeskill",
            name="verified_test_attempt",
            field=models.ForeignKey(
                blank=True,
                help_text="The test attempt that verified this skill",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_resume_skills",
                to="skill_tests.testattempt",
            ),
        ),
    ]
