# Generated by Django 5.0.7 on 2025-10-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("name", "language")},
        ),
    ]
