# Generated by Django 5.0.7 on 2025-10-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_alter_emailtemplate_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(
                help_text="Please enter the correct name, for example: 'reset-password' or 'general'",
                max_length=100,
            ),
        ),
    ]
