# Generated by Django 5.0.7 on 2025-10-13 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_alter_emailtemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="body",
            field=models.FileField(
                help_text="Upload an HTML file for the email body.",
                upload_to="email_templates/",
                validators=[django.core.validators.FileExtensionValidator(("html",))],
            ),
        ),
    ]
