# Generated by Django 5.0.7 on 2026-01-15 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_alter_emailtemplate_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobQueue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the job",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("edu_analytics", "EduPartner Analytics"),
                            ("hr_analytics", "HR Analytics"),
                            ("email_notification", "Email Notification"),
                        ],
                        help_text="Type of the job (edu_analytics, hr_analytics, etc.)",
                        max_length=50,
                    ),
                ),
                ("target_date", models.DateField(help_text="The date the data is for")),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the target entity (faculty_id, company_id, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the target entity for easier identification",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the job",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum number of retries before alerting"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of the last attempt", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message from the last failed attempt",
                        null=True,
                    ),
                ),
                (
                    "rq_job_id",
                    models.CharField(
                        blank=True,
                        help_text="RQ job ID for tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the payload to detect duplicates",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "alert_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an alert was sent for exceeded retries",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Queue",
                "verbose_name_plural": "Job Queues",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_type", "status"],
                        name="general_job_job_typ_a1afb3_idx",
                    ),
                    models.Index(
                        fields=["target_date", "status"],
                        name="general_job_target__5d8b48_idx",
                    ),
                    models.Index(
                        fields=["status", "retry_count"],
                        name="general_job_status_fec634_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="jobqueue",
            constraint=models.UniqueConstraint(
                fields=("job_type", "target_date", "target_id"),
                name="unique_job_per_target_per_day",
            ),
        ),
    ]
