# Generated by Django 5.1.15 on 2026-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_add_job_queue_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyAnalyticsSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vacancy_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the vacancy being tracked",
                        unique=True,
                    ),
                ),
                (
                    "deactivation_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when is_active=False was successfully sent to HR Analytics. NULL means the final send has not yet been delivered.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vacancy Analytics Sync",
                "verbose_name_plural": "Vacancy Analytics Syncs",
                "db_table": "general_vacancy_analytics_sync",
            },
        ),
    ]
