# Generated by Django 5.1.15 on 2026-03-31 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_alter_applicationdocument_title"),
        ("authentication", "0027_userconsent_inherit_abstractbasemodel"),
        ("general", "0006_add_vacancy_analytics_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationSummaryNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this notification record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the notification was sent",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="The job application that was included in a summary email",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_notifications",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="The recruiter who received the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_notifications",
                        to="authentication.recruiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Summary Notification",
                "verbose_name_plural": "Application Summary Notifications",
                "indexes": [
                    models.Index(
                        fields=["application"], name="general_app_applica_4ef4d6_idx"
                    ),
                    models.Index(
                        fields=["recruiter"], name="general_app_recruit_835219_idx"
                    ),
                    models.Index(
                        fields=["notified_at"], name="general_app_notifie_505211_idx"
                    ),
                ],
                "unique_together": {("application", "recruiter")},
            },
        ),
    ]
