# Generated by Django 5.1.15 on 2026-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0009_alter_jobqueue_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobqueue",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("edu_analytics", "EduPartner Analytics"),
                    ("hr_analytics", "HR Analytics"),
                    ("email_notification", "Email Notification"),
                    ("resume_generation", "Resume Generation"),
                    ("candidate_evaluation", "Candidate AI Evaluation"),
                ],
                help_text="Type of the job (edu_analytics, hr_analytics, etc.)",
                max_length=50,
            ),
        ),
    ]
