# Generated by Django 5.1.15 on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_customuser_preferred_language"),
        ("general", "0010_alter_jobqueue_job_type"),
        ("resumes", "0025_resume_is_reviewed"),
        ("skills", "0002_skill_is_active"),
        ("vacancies", "0021_add_vacancy_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateSkillRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "normalized_skill_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("hh", "HeadHunter"),
                            ("workxplorer", "WorkXplorer"),
                            ("manual", "Manual"),
                        ],
                        default="hh",
                        max_length=30,
                    ),
                ),
                ("source_key", models.CharField(blank=True, default="", max_length=255)),
                ("language", models.CharField(default="uz", max_length=5)),
                ("vacancy_count", models.PositiveIntegerField(default=0)),
                ("minimum_years", models.PositiveIntegerField(default=0)),
                (
                    "proficiency_level",
                    models.CharField(default="UNDEFINED", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("added_to_resume", "Added to resume"),
                            ("marked", "Marked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_recommendations",
                        to="authentication.candidate",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_recommendations",
                        to="resumes.resume",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_recommendations",
                        to="skills.skill",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_skill_recommendations",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Skill Recommendation",
                "verbose_name_plural": "Candidate Skill Recommendations",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "resume", "status"],
                        name="general_can_candida_d6d215_idx",
                    ),
                    models.Index(
                        fields=["source", "normalized_skill_name"],
                        name="general_can_source_5eeb5b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "candidate",
                            "resume",
                            "source",
                            "normalized_skill_name",
                        ),
                        name="unique_candidate_resume_skill_recommendation",
                    )
                ],
            },
        ),
    ]
