# Generated by Django 5.1.15 on 2026-05-21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
        ("general", "0011_candidate_skill_recommendation"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS general_hhmarketsnapshot (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at timestamp with time zone NOT NULL,
                            updated_at timestamp with time zone NOT NULL,
                            query varchar(255) NOT NULL,
                            normalized_query varchar(255) NOT NULL,
                            area_id varchar(50) NOT NULL DEFAULT '97',
                            language varchar(5) NOT NULL DEFAULT 'uz',
                            vacancy_count integer NOT NULL DEFAULT 0,
                            vacancies jsonb NOT NULL DEFAULT '[]'::jsonb,
                            skills jsonb NOT NULL DEFAULT '[]'::jsonb,
                            requirements jsonb NOT NULL DEFAULT '[]'::jsonb,
                            status varchar(20) NOT NULL DEFAULT 'success',
                            error_message text NOT NULL DEFAULT '',
                            fetched_at timestamp with time zone NOT NULL,
                            expires_at timestamp with time zone NULL,
                            domain_id bigint NULL
                        );

                        CREATE INDEX IF NOT EXISTS general_hhm_normali_e63a5a_idx
                            ON general_hhmarketsnapshot
                            (normalized_query, area_id, status, fetched_at DESC);

                        CREATE INDEX IF NOT EXISTS general_hhm_domain__a2be6c_idx
                            ON general_hhmarketsnapshot
                            (domain_id, status, fetched_at DESC);

                        CREATE INDEX IF NOT EXISTS general_hhmarketsnapshot_area_id_idx
                            ON general_hhmarketsnapshot (area_id);

                        CREATE INDEX IF NOT EXISTS general_hhmarketsnapshot_fetched_at_idx
                            ON general_hhmarketsnapshot (fetched_at);

                        CREATE INDEX IF NOT EXISTS general_hhmarketsnapshot_expires_at_idx
                            ON general_hhmarketsnapshot (expires_at);

                        CREATE INDEX IF NOT EXISTS general_hhmarketsnapshot_normalized_query_idx
                            ON general_hhmarketsnapshot (normalized_query);

                        CREATE INDEX IF NOT EXISTS general_hhmarketsnapshot_status_idx
                            ON general_hhmarketsnapshot (status);

                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1
                                FROM pg_constraint
                                WHERE conname = 'general_hhmarketsnapshot_domain_id_fk'
                            ) THEN
                                ALTER TABLE general_hhmarketsnapshot
                                    ADD CONSTRAINT general_hhmarketsnapshot_domain_id_fk
                                    FOREIGN KEY (domain_id)
                                    REFERENCES domain_domain(id)
                                    DEFERRABLE INITIALLY DEFERRED;
                            END IF;
                        END
                        $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="HHMarketSnapshot",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                auto_now_add=True,
                                verbose_name="Created at",
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(
                                auto_now=True,
                                verbose_name="Updated at",
                            ),
                        ),
                        ("query", models.CharField(max_length=255)),
                        (
                            "normalized_query",
                            models.CharField(db_index=True, max_length=255),
                        ),
                        (
                            "area_id",
                            models.CharField(
                                db_index=True,
                                default="97",
                                max_length=50,
                            ),
                        ),
                        ("language", models.CharField(default="uz", max_length=5)),
                        ("vacancy_count", models.PositiveIntegerField(default=0)),
                        ("vacancies", models.JSONField(blank=True, default=list)),
                        ("skills", models.JSONField(blank=True, default=list)),
                        ("requirements", models.JSONField(blank=True, default=list)),
                        (
                            "status",
                            models.CharField(
                                choices=[("success", "Success"), ("failed", "Failed")],
                                db_index=True,
                                default="success",
                                max_length=20,
                            ),
                        ),
                        ("error_message", models.TextField(blank=True, default="")),
                        (
                            "fetched_at",
                            models.DateTimeField(
                                db_index=True,
                                default=django.utils.timezone.now,
                            ),
                        ),
                        (
                            "expires_at",
                            models.DateTimeField(
                                blank=True,
                                db_index=True,
                                null=True,
                            ),
                        ),
                        (
                            "domain",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="hh_market_snapshots",
                                to="domain.domain",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "HH Market Snapshot",
                        "verbose_name_plural": "HH Market Snapshots",
                        "ordering": ["-fetched_at"],
                        "indexes": [
                            models.Index(
                                fields=[
                                    "normalized_query",
                                    "area_id",
                                    "status",
                                    "-fetched_at",
                                ],
                                name="general_hhm_normali_e63a5a_idx",
                            ),
                            models.Index(
                                fields=["domain", "status", "-fetched_at"],
                                name="general_hhm_domain__a2be6c_idx",
                            ),
                        ],
                    },
                ),
            ],
        ),
    ]
