# Generated by Django 5.1.15 on 2026-05-25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
        ("general", "0013_repair_candidate_skill_recommendation_columns"),
        ("skills", "0002_skill_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainMarketSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("hh", "HeadHunter")],
                        db_index=True,
                        default="hh",
                        max_length=30,
                    ),
                ),
                ("scope_key", models.CharField(db_index=True, max_length=255)),
                ("query", models.CharField(max_length=255)),
                (
                    "normalized_query",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "area_id",
                    models.CharField(db_index=True, default="97", max_length=50),
                ),
                ("language", models.CharField(default="uz", max_length=5)),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "normalized_skill_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("vacancy_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_skills",
                        to="domain.domain",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_skill_sources",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Market Skill",
                "verbose_name_plural": "Domain Market Skills",
                "ordering": ["-vacancy_count", "skill_name"],
                "indexes": [
                    models.Index(
                        fields=["source", "area_id", "scope_key", "is_active"],
                        name="general_dms_source_scope_idx",
                    ),
                    models.Index(
                        fields=["domain", "source", "is_active", "-vacancy_count"],
                        name="general_dms_domain_active_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=[
                            "source",
                            "area_id",
                            "scope_key",
                            "normalized_skill_name",
                        ],
                        name="unique_market_skill_per_scope",
                    )
                ],
            },
        ),
    ]
