# Generated by Django 5.1.15 on 2026-05-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0014_domain_market_skill"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HHMarketSnapshot",
        ),
    ]
