# Generated by Django 5.1.15 on 2026-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0015_delete_hh_market_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainmarketskill",
            name="skill",
        ),
        migrations.AlterField(
            model_name="domainmarketskill",
            name="source",
            field=models.CharField(db_index=True, default="hh", max_length=30),
        ),
    ]
