# Generated by Django 5.2.13 on 2026-06-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0016_remove_domainmarketskill_skill_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CandidateSkillRecommendation",
        ),
    ]
