# Generated by Django 5.1.15 on 2026-06-18 06:38

import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0017_delete_candidateskillrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSalaryCache",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        db_index=True,
                        help_text="Target role / search query, e.g. 'Python Developer'",
                        max_length=255,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="both",
                        help_text="Data source: hh, platform, both",
                        max_length=20,
                    ),
                ),
                (
                    "median_salary_uzs",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Market median salary in UZS",
                        max_digits=15,
                    ),
                ),
                (
                    "salary_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum of collected salary_from values",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "salary_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum of collected salary_to values",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "sample_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of salary data points used"
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Salary Cache",
                "verbose_name_plural": "Market Salary Caches",
                "indexes": [
                    models.Index(
                        fields=["role", "-created_at"],
                        name="general_mar_role_124862_idx",
                    )
                ],
            },
        ),
    ]
