# Generated by Django 5.2.17 on 2026-08-19 07:52

import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0018_marketsalarycache"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatUzSectorSalary",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sector_code",
                    models.CharField(
                        db_index=True,
                        help_text="stat.uz sector classification code, matched against Domain.sector_code",
                        max_length=50,
                    ),
                ),
                (
                    "sector_name",
                    models.CharField(
                        help_text="Human-readable sector name as published by stat.uz",
                        max_length=255,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("quarterly", "Quarterly"), ("yearly", "Yearly")],
                        default="quarterly",
                        max_length=20,
                    ),
                ),
                (
                    "period_label",
                    models.CharField(
                        help_text="Reporting period as published, e.g. '2026-Q2' or '2025'",
                        max_length=20,
                    ),
                ),
                (
                    "avg_salary_uzs",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average monthly salary in UZS for this sector/period",
                        max_digits=15,
                    ),
                ),
                (
                    "source_dataset_id",
                    models.CharField(
                        help_text="stat.uz SDMX dataset id this row was sourced from",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stat.uz Sector Salary",
                "verbose_name_plural": "Stat.uz Sector Salaries",
                "indexes": [
                    models.Index(
                        fields=["sector_code", "-created_at"],
                        name="general_sta_sector__ee21c6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sector_code", "period_type", "period_label"),
                        name="unique_sector_period",
                    )
                ],
            },
        ),
    ]
