# Generated by Django 5.1.15 on 2026-02-20 07:31

import django.db.models.deletion
import django.utils.timezone
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0022_customuser_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this feature",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code identifier used in permission checks (e.g., 'headhunting_access', 'company_analytics')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the feature", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of what this feature provides",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[("company", "Company"), ("candidate", "Candidate")],
                        help_text="Whether this feature applies to company or candidate plans",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this feature is currently in use",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Feature",
                "verbose_name_plural": "Subscription Features",
                "ordering": ["feature_type", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="subscriptio_code_3720ac_idx"),
                    models.Index(
                        fields=["feature_type", "is_active"],
                        name="subscriptio_feature_d54ee0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this plan-feature link",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this feature is enabled for this plan",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional JSON configuration for this feature within the plan. e.g., {'max_invitations_per_day': 50}",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="The feature included in this plan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_features",
                        to="subscriptions.subscriptionfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this plan",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the plan (e.g., 'Free', 'Basic', 'Pro')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'company-free', 'company-basic'). Used in code to reference specific plans.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("company", "Company"), ("candidate", "Candidate")],
                        help_text="Whether this plan is for companies or candidates",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of what this plan offers",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available for purchase/assignment",
                    ),
                ),
                (
                    "max_admins",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of admin-level recruiters allowed. Only relevant for company plans.",
                    ),
                ),
                (
                    "max_recruiters",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of recruiter-level users allowed. Only relevant for company plans.",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price of this plan (0 for free plans)",
                        max_digits=10,
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("lifetime", "Lifetime"),
                        ],
                        help_text="Billing cycle for paid plans. Null for free plans.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which plans are displayed (lower = first)",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Features included in this plan",
                        related_name="plans",
                        through="subscriptions.PlanFeature",
                        to="subscriptions.subscriptionfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["display_order", "price"],
            },
        ),
        migrations.AddField(
            model_name="planfeature",
            name="plan",
            field=models.ForeignKey(
                help_text="The subscription plan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_features",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="CompanySubscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this subscription",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending Payment"),
                        ],
                        default="active",
                        help_text="Current status of the subscription",
                        max_length=20,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the subscription period starts",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscription expires. Null = no expiry (free plans).",
                        null=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to payment transaction (for future payment integration)",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this subscription belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="authentication.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The subscription plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Subscription",
                "verbose_name_plural": "Company Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateSubscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this subscription",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending Payment"),
                        ],
                        default="active",
                        help_text="Current status of the subscription",
                        max_length=20,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the subscription period starts",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscription expires. Null = no expiry (free plans).",
                        null=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to payment transaction (for future payment integration)",
                        max_length=255,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="The candidate this subscription belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="authentication.candidate",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The subscription plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Subscription",
                "verbose_name_plural": "Candidate Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionSeatAssignment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this seat assignment",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("recruiter", "Recruiter")],
                        help_text="Whether this is an admin or recruiter seat",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this seat assignment is currently active",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="The recruiter assigned to this seat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_seats",
                        to="authentication.recruiter",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="The subscription this seat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_assignments",
                        to="subscriptions.companysubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat Assignment",
                "verbose_name_plural": "Seat Assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["plan_type", "is_active"], name="subscriptio_plan_ty_21d135_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(fields=["slug"], name="subscriptio_slug_3cc181_idx"),
        ),
        migrations.AddConstraint(
            model_name="planfeature",
            constraint=models.UniqueConstraint(
                fields=("plan", "feature"), name="unique_plan_feature"
            ),
        ),
        migrations.AddIndex(
            model_name="companysubscription",
            index=models.Index(
                fields=["company", "status"], name="subscriptio_company_1109ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companysubscription",
            index=models.Index(
                fields=["status", "expires_at"], name="subscriptio_status_8baa92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatesubscription",
            index=models.Index(
                fields=["candidate", "status"], name="subscriptio_candida_81e090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionseatassignment",
            index=models.Index(
                fields=["subscription", "seat_type", "is_active"],
                name="subscriptio_subscri_0cda3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionseatassignment",
            index=models.Index(
                fields=["recruiter", "is_active"], name="subscriptio_recruit_b1f78f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionseatassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("subscription", "recruiter"),
                name="unique_active_seat_per_recruiter",
            ),
        ),
    ]
