# Generated by Django 5.1.15 on 2026-04-30 07:04

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_customuser_preferred_language"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateFeatureUsage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this usage record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_month",
                    models.DateField(
                        help_text="First day of the calendar month this usage belongs to"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this feature was used in this month",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="The candidate whose usage is being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usage",
                        to="authentication.candidate",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        help_text="The feature being tracked (e.g. ai_resume_generation)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_usage",
                        to="subscriptions.subscriptionfeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Feature Usage",
                "verbose_name_plural": "Candidate Feature Usage",
                "ordering": ["-usage_month", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "feature"],
                        name="subscriptio_candida_9b07ee_idx",
                    ),
                    models.Index(
                        fields=["usage_month"], name="subscriptio_usage_m_9337ed_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "feature", "usage_month"),
                        name="unique_candidate_feature_usage_month",
                    )
                ],
            },
        ),
    ]
