# Generated by Django 5.1.15 on 2026-05-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_candidatefeatureusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysubscription",
            name="has_design",
            field=models.BooleanField(
                default=False,
                help_text="Enable branded design for this company's vacancies (banner + styled cards).",
            ),
        ),
    ]
