# Generated by Django 5.1.15 on 2026-06-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_companysubscription_has_design"),
        ("subscriptions", "0003_rename_reason_limit_to_template_limit"),
    ]

    operations = []
