# Generated by Django 5.1.15 on 2026-07-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_companyfeatureusage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="companyfeatureusage",
            new_name="subscriptio_company_80e547_idx",
            old_name="subscriptio_company_cfu_idx",
        ),
        migrations.RenameIndex(
            model_name="companyfeatureusage",
            new_name="subscriptio_usage_m_cf59eb_idx",
            old_name="subscriptio_cfu_month_idx",
        ),
    ]
