# Generated by Django 5.1.15 on 2026-02-23 10:28

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0022_customuser_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short title for the reason template",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description or template text for recruiter notes",
                        verbose_name="Description",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this reason template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_reasons",
                        to="authentication.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reason",
                "verbose_name_plural": "Reasons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="hr_template_company_a0753d_idx",
                    )
                ],
            },
        ),
    ]
