# Generated by Django 5.1.15 on 2026-02-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reason",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("INTERVIEWED", "Interviewed"),
                    ("OFFERED", "Offered"),
                    ("OFFER_ACCEPTED", "Offer Accepted"),
                    ("OFFER_REJECTED", "Offer Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("REJECTED", "Rejected"),
                ],
                default=1,
                help_text="The application status this reason is associated with",
                max_length=50,
                verbose_name="Application Status",
            ),
            preserve_default=False,
        ),
    ]
