# Generated by Django 5.1.15 on 2026-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_templates", "0002_reason_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reason",
            name="status",
            field=models.CharField(
                choices=[
                    ("REJECTED", "Rejected"),
                    ("ACCEPTED", "Accepted"),
                    ("OTHER", "Other"),
                ],
                help_text="The application status this reason is associated with",
                max_length=50,
                verbose_name="Application Status",
            ),
        ),
    ]
