# Generated by Django 5.2.13 on 2026-05-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0025_add_ai_failed_status_category"),
        ("authentication", "0033_customuser_preferred_language"),
        ("hr_templates", "0005_alter_reason_status"),
    ]

    operations = [
        # Step 1: Add new fields to existing Reason model
        migrations.AddField(
            model_name="reason",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("STATUS_CHANGE", "Status Change Template"),
                    ("INVITATION", "Invitation Template"),
                ],
                default="STATUS_CHANGE",
                help_text="Whether this template is for status changes or invitations",
                max_length=20,
                verbose_name="Template Type",
            ),
        ),
        migrations.AddField(
            model_name="reason",
            name="application_status",
            field=models.ForeignKey(
                blank=True,
                help_text="The company-specific application status this template is associated with (required for STATUS_CHANGE templates)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="applications.applicationstatusmodel",
                verbose_name="Application Status",
            ),
        ),
        # Step 2: Make status nullable (legacy field)
        migrations.AlterField(
            model_name="reason",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REJECTED", "Rejected"),
                    ("OFFERED", "Offered"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                ],
                help_text="DEPRECATED: Legacy status field. Use application_status instead.",
                max_length=50,
                null=True,
                verbose_name="Legacy Status",
            ),
        ),
        # Step 3: Rename Reason to Template
        migrations.RenameModel(
            old_name="Reason",
            new_name="Template",
        ),
        # Step 4: Add indexes
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["company", "template_type"], name="hr_template_company_8aaf1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["company", "template_type", "application_status"],
                name="hr_template_company_1f61e9_idx",
            ),
        ),
        # Step 5: Add unique constraint for STATUS_CHANGE templates
        migrations.AddConstraint(
            model_name="template",
            constraint=models.UniqueConstraint(
                condition=models.Q(("template_type", "STATUS_CHANGE")),
                fields=("company", "template_type", "application_status"),
                name="unique_status_template_per_company",
            ),
        ),
    ]
