# Generated by Django 5.1.15 on 2026-05-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_customuser_preferred_language"),
        ("hr_templates", "0008_remove_status_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="template",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
            },
        ),
        migrations.RenameIndex(
            model_name="template",
            new_name="hr_template_company_890211_idx",
            old_name="hr_template_company_a0753d_idx",
        ),
        migrations.AlterField(
            model_name="template",
            name="company",
            field=models.ForeignKey(
                help_text="The company this template belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="authentication.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description or template text. Supports {{candidate_name}}, {{position}}, {{company_name}} variables.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="title",
            field=models.CharField(
                help_text="Short title for the template",
                max_length=255,
                verbose_name="Title",
            ),
        ),
    ]
