KNOWN_PLATFORMS = frozenset({
    # --- General learning platforms ---
    "roadmap.sh",
    "freecodecamp.org", "www.freecodecamp.org",
    "coursera.org", "www.coursera.org",
    "udemy.com", "www.udemy.com",
    "pluralsight.com", "www.pluralsight.com",
    "edx.org", "www.edx.org",
    "khanacademy.org", "www.khanacademy.org",
    "skillshare.com", "www.skillshare.com",
    "linkedin.com", "www.linkedin.com", "learning.linkedin.com",
    "udacity.com", "www.udacity.com",
    "codecademy.com", "www.codecademy.com",
    "brilliant.org", "www.brilliant.org",
    "lynda.com", "www.lynda.com",
    "alison.com", "www.alison.com",
    "futurelearn.com", "www.futurelearn.com",
    "openlearn.open.ac.uk",
    "ocw.mit.edu",
    "nptel.ac.in",
    "swayam.gov.in",

    # --- Tech / software development ---
    "developer.mozilla.org",
    "docs.python.org",
    "react.dev",
    "nextjs.org", "www.nextjs.org",
    "nodejs.org", "www.nodejs.org",
    "docker.com", "www.docker.com", "docs.docker.com",
    "kubernetes.io", "www.kubernetes.io",
    "git-scm.com", "www.git-scm.com",
    "github.com", "www.github.com",
    "gitlab.com", "www.gitlab.com",
    "stackoverflow.com", "www.stackoverflow.com",
    "dev.to", "www.dev.to",
    "w3schools.com", "www.w3schools.com",
    "geeksforgeeks.org", "www.geeksforgeeks.org",
    "tutorialspoint.com", "www.tutorialspoint.com",
    "atlassian.com", "www.atlassian.com",
    "postman.com", "www.postman.com",
    "graphql.org", "www.graphql.org",
    "typescriptlang.org", "www.typescriptlang.org",
    "mongodb.com", "www.mongodb.com",
    "redis.io", "www.redis.io",
    "nginx.org", "www.nginx.org",
    "nginx.com", "www.nginx.com",
    "digitalocean.com", "www.digitalocean.com",
    "smashingmagazine.com", "www.smashingmagazine.com",
    "css-tricks.com", "www.css-tricks.com",
    "leetcode.com", "www.leetcode.com",
    "hackerrank.com", "www.hackerrank.com",
    "realpython.com", "www.realpython.com",
    "rust-lang.org", "www.rust-lang.org", "doc.rust-lang.org",
    "go.dev",
    "learn.microsoft.com", "docs.microsoft.com",
    "developer.apple.com",
    "developer.android.com",
    "cloud.google.com",
    "aws.amazon.com",
    "docs.aws.amazon.com",
    "azure.microsoft.com",
    "terraform.io", "www.terraform.io", "developer.hashicorp.com",
    "ansible.com", "www.ansible.com", "docs.ansible.com",
    "pytest.org", "docs.pytest.org",
    "djangoproject.com", "www.djangoproject.com", "docs.djangoproject.com",
    "fastapi.tiangolo.com",
    "flask.palletsprojects.com",
    "spring.io",
    "laravel.com", "www.laravel.com",
    "vuejs.org", "www.vuejs.org",
    "angular.io",
    "svelte.dev",
    "expressjs.com", "www.expressjs.com",

    # --- Data science / AI / ML ---
    "kaggle.com", "www.kaggle.com",
    "scikit-learn.org",
    "pytorch.org", "www.pytorch.org",
    "tensorflow.org", "www.tensorflow.org",
    "huggingface.co",
    "fast.ai", "www.fast.ai",
    "deeplearning.ai", "www.deeplearning.ai",
    "datacamp.com", "www.datacamp.com",
    "mode.com", "www.mode.com",
    "towardsdatascience.com", "www.towardsdatascience.com",

    # --- Finance & banking ---
    "investopedia.com", "www.investopedia.com",
    "corporatefinanceinstitute.com", "www.corporatefinanceinstitute.com",
    "cfainstitute.org", "www.cfainstitute.org",
    "cfa.institute",
    "accountingcoach.com", "www.accountingcoach.com",
    "wallstreetmojo.com", "www.wallstreetmojo.com",
    "financialmodeling.com", "www.financialmodeling.com",
    "smartasset.com", "www.smartasset.com",
    "nerdwallet.com", "www.nerdwallet.com",
    "fool.com", "www.fool.com",
    "morganstanley.com", "www.morganstanley.com",
    "goldmansachs.com", "www.goldmansachs.com",
    "imf.org", "www.imf.org",
    "worldbank.org", "www.worldbank.org",
    "bis.org", "www.bis.org",
    "federalreserve.gov", "www.federalreserve.gov",
    "sec.gov", "www.sec.gov",

    # --- Healthcare & medicine ---
    "who.int", "www.who.int",
    "cdc.gov", "www.cdc.gov",
    "nih.gov", "www.nih.gov",
    "pubmed.ncbi.nlm.nih.gov",
    "medlineplus.gov",
    "mayoclinic.org", "www.mayoclinic.org",
    "webmd.com", "www.webmd.com",
    "healthline.com", "www.healthline.com",
    "medscape.com", "www.medscape.com",
    "bmj.com", "www.bmj.com",
    "nejm.org", "www.nejm.org",
    "thelancet.com", "www.thelancet.com",
    "jamanetwork.com", "www.jamanetwork.com",
    "uptodate.com", "www.uptodate.com",
    "osmosis.org", "www.osmosis.org",
    "amboss.com", "www.amboss.com",
    "kenhub.com", "www.kenhub.com",

    # --- Law & legal ---
    "law.cornell.edu",
    "findlaw.com", "www.findlaw.com",
    "justia.com", "www.justia.com",
    "law.com", "www.law.com",
    "oyez.org", "www.oyez.org",
    "scotusblog.com", "www.scotusblog.com",
    "courtlistener.com", "www.courtlistener.com",
    "westlaw.com", "www.westlaw.com",
    "lexisnexis.com", "www.lexisnexis.com",

    # --- Business & management ---
    "hbr.org", "www.hbr.org",
    "mckinsey.com", "www.mckinsey.com",
    "bcg.com", "www.bcg.com",
    "bain.com", "www.bain.com",
    "mit.edu", "www.mit.edu",
    "harvard.edu", "www.harvard.edu",
    "wharton.upenn.edu",
    "insead.edu", "www.insead.edu",
    "imd.org", "www.imd.org",

    # --- Science & engineering ---
    "nature.com", "www.nature.com",
    "science.org", "www.science.org",
    "arxiv.org", "www.arxiv.org",
    "ieee.org", "www.ieee.org", "ieeexplore.ieee.org",
    "acm.org", "www.acm.org", "dl.acm.org",
    "researchgate.net", "www.researchgate.net",
    "scholar.google.com",
    "coursehero.com", "www.coursehero.com",
    "physicsclassroom.com", "www.physicsclassroom.com",
    "chemguide.co.uk", "www.chemguide.co.uk",

    # --- Design & UX ---
    "nngroup.com", "www.nngroup.com",
    "uxdesign.cc",
    "figma.com", "www.figma.com",
    "adobe.com", "www.adobe.com",
    "interaction-design.org", "www.interaction-design.org",
    "awwwards.com", "www.awwwards.com",
    "dribbble.com", "www.dribbble.com",
    "behance.net", "www.behance.net",

    # --- Credible news & general knowledge ---
    "bbc.com", "www.bbc.com", "bbc.co.uk", "www.bbc.co.uk",
    "reuters.com", "www.reuters.com",
    "apnews.com", "www.apnews.com",
    "theguardian.com", "www.theguardian.com",
    "nytimes.com", "www.nytimes.com",
    "economist.com", "www.economist.com",
    "ft.com", "www.ft.com",
    "wsj.com", "www.wsj.com",
    "bloomberg.com", "www.bloomberg.com",
    "nationalgeographic.com", "www.nationalgeographic.com",
    "scientificamerican.com", "www.scientificamerican.com",
    "britannica.com", "www.britannica.com",
    "wikipedia.org", "en.wikipedia.org",

    # --- Languages & writing ---
    "duolingo.com", "www.duolingo.com",
    "babbel.com", "www.babbel.com",
    "busuu.com", "www.busuu.com",
    "italki.com", "www.italki.com",
    "grammarly.com", "www.grammarly.com",
    "purdue.edu", "owl.purdue.edu",

    # --- Project management & productivity ---
    "pmi.org", "www.pmi.org",
    "prince2.com", "www.prince2.com",
    "scrumalliance.org", "www.scrumalliance.org",
    "scrum.org", "www.scrum.org",
    "agilealliance.org", "www.agilealliance.org",
    "notion.so", "www.notion.so",
    "trello.com", "www.trello.com",

    # --- Cybersecurity ---
    "owasp.org", "www.owasp.org",
    "sans.org", "www.sans.org",
    "cybrary.it", "www.cybrary.it",
    "hackthebox.com", "www.hackthebox.com",
    "tryhackme.com", "www.tryhackme.com",
    "nist.gov", "www.nist.gov", "csrc.nist.gov",
    "cisa.gov", "www.cisa.gov",

    # --- Marketing & SEO ---
    "hubspot.com", "www.hubspot.com", "blog.hubspot.com",
    "moz.com", "www.moz.com",
    "semrush.com", "www.semrush.com",
    "ahrefs.com", "www.ahrefs.com",
    "marketingland.com", "www.marketingland.com",
    "contentmarketinginstitute.com", "www.contentmarketinginstitute.com",
    "socialmediaexaminer.com", "www.socialmediaexaminer.com",

    # --- General reference ---
    "medium.com", "www.medium.com",
    "substack.com", "www.substack.com",
    "quora.com", "www.quora.com",
    "reddit.com", "www.reddit.com",
})

PARKING_DOMAINS = frozenset({
    "godaddy.com", "www.godaddy.com",
    "dan.com", "www.dan.com",
    "sedoparking.com", "www.sedoparking.com",
    "afternic.com", "www.afternic.com",
    "hugedomains.com", "www.hugedomains.com",
    "sedo.com", "www.sedo.com",
    "undeveloped.com", "www.undeveloped.com",
    "domainmarket.com", "www.domainmarket.com",
})

YOUTUBE_DOMAINS = frozenset({
    "youtube.com", "www.youtube.com", "youtu.be",
    "m.youtube.com", "music.youtube.com",
})
