# Generated by Django 5.0.7 on 2025-10-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_delete_recruiterprofile"),
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrCreatedProfession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the profession created by HR",
                        max_length=255,
                        verbose_name="Profession Name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the profession",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company that created this profession",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_created_professions",
                        to="authentication.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The recruiter who created this profession",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_professions",
                        to="authentication.recruiter",
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Created Profession",
                "verbose_name_plural": "HR Created Professions",
                "ordering": ["name"],
            },
        ),
    ]
