# Generated by Django 5.0.7 on 2026-01-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_hrcreatedprofession"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the domain",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the domain",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="description_uz",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the domain",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="name_en",
            field=models.CharField(
                help_text="Domain name (e.g., IT, Healthcare, Finance)",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="name_ru",
            field=models.CharField(
                help_text="Domain name (e.g., IT, Healthcare, Finance)",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="name_uz",
            field=models.CharField(
                help_text="Domain name (e.g., IT, Healthcare, Finance)",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
