# Generated by Django 5.1.15 on 2026-06-20 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0003_domain_description_en_domain_description_ru_and_more"),
        ("skills", "0005_learningmaterial_title_ru_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The skill category that best represents this domain's primary skills",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domains",
                to="skills.skillcategory",
                verbose_name="Skill Category",
            ),
        ),
    ]
