# Generated by Django 5.2.17 on 2026-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0004_add_domain_category_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="sector_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Official statistics sector this domain maps to (e.g. stat.uz sector classification), used to cross-reference market salary estimates against government wage data. Assigned once per domain, not per request.",
                max_length=50,
                null=True,
                verbose_name="Sector Code",
            ),
        ),
    ]
