# Generated by Django 5.0.7 on 2025-11-19 18:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0011_candidate_faculty"),
        ("resumes", "0008_resume_updated_at_alter_resume_created_at"),
        ("vacancies", "0010_vacancyview"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this application",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the candidate submitted their application",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this application was last modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                            ("INTERVIEWED", "Interviewed"),
                            ("TECHNICAL_TEST", "Technical Test"),
                            ("FINAL_REVIEW", "Final Review"),
                            ("OFFERED", "Offered"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        help_text="Current status of this application in the hiring process",
                        max_length=20,
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        blank=True,
                        help_text="Optional cover letter submitted with this application",
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional portfolio or personal website URL",
                        max_length=500,
                    ),
                ),
                (
                    "additional_documents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store references to additional documents (file paths, URLs, etc.)",
                    ),
                ),
                (
                    "recruiter_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for recruiters (not visible to candidates)",
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Candidate's salary expectation for this specific role",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "earliest_start_date",
                    models.DateField(
                        blank=True,
                        help_text="When the candidate can start working",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this application is still active in the system",
                    ),
                ),
                (
                    "in_review_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the application status changed from 'Applied' to 'Under Review'",
                        null=True,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="The candidate who submitted this application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="authentication.candidate",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recruiter who last updated this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_applications",
                        to="authentication.recruiter",
                    ),
                ),
                (
                    "resume_used",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific resume version used for this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="resumes.resume",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        help_text="The job vacancy this application is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CERTIFICATE", "Certificate"),
                            ("PORTFOLIO", "Portfolio"),
                            ("REFERENCE", "Reference Letter"),
                            ("COVER_LETTER", "Cover Letter"),
                            ("TRANSCRIPT", "Academic Transcript"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title for this document", max_length=200
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded document file",
                        upload_to="application_documents/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["candidate"], name="application_candida_670028_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["vacancy"], name="application_vacancy_b224c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["status"], name="application_status_e72231_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["applied_at"], name="application_applied_4703e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["vacancy", "status"], name="application_vacancy_fe9d03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["candidate", "status"], name="application_candida_cb317b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobapplication",
            constraint=models.UniqueConstraint(
                fields=("candidate", "vacancy"),
                name="unique_candidate_vacancy_application",
            ),
        ),
    ]
