# Generated by Django 5.0.7 on 2025-11-22 14:04

import utils.fields.uuid7_field
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdocument",
            name="id",
            field=utils.fields.uuid7_field.UUIDField(
                default=uuid.uuid5, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="id",
            field=utils.fields.uuid7_field.UUIDField(
                default=utils.fields.uuid7_field.uuidv7,
                editable=False,
                help_text="Unique identifier for this application",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
