# Generated by Django 5.0.7 on 2025-11-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="hired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the application status changed to 'Accepted' (hired date)",
                null=True,
            ),
        ),
    ]
