# Generated by Django 5.0.7 on 2025-11-22 14:16

import utils.fields.uuid7_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_applicationdocument_id_alter_jobapplication_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdocument",
            name="id",
            field=utils.fields.uuid7_field.UUIDField(
                default=utils.fields.uuid7_field.uuidv7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
