# Generated by Django 5.0.7 on 2025-11-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_add_hired_at_field"),
        ("applications", "0003_alter_applicationdocument_id"),
    ]

    operations = []
