# Generated by Django 5.0.7 on 2025-12-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_merge_20251129_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLIED", "Applied"),
                    ("REJECTED", "Rejected"),
                    ("INTERVIEW_SCHEDULED", "Interview Scheduled"),
                    ("INTERVIEWED", "Interviewed"),
                    ("OFFERED", "Offered"),
                    ("OFFER_ACCEPTED", "Offer Accepted"),
                    ("OFFER_REJECTED", "Offer Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                ],
                default="APPLIED",
                help_text="Current status of this application in the hiring process",
                max_length=20,
            ),
        ),
    ]
