# Generated by Django 5.0.7 on 2026-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="salary_currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("UZS", "UZS"), ("EUR", "EUR")],
                default="UZS",
                help_text="Currency for the expected salary",
                max_length=5,
            ),
        ),
    ]
