# Generated by Django 5.0.7 on 2026-01-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_jobapplication_salary_currency"),
        ("authentication", "0018_remove_company_type_field"),
        ("resumes", "0016_resume_is_main_alter_resumecertificate_file_and_more"),
        ("vacancies", "0012_vacancyview_viewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="kanban_position",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Position of the application in the Kanban board column. Lower values appear first. Used for drag-and-drop reordering.",
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "kanban_position"],
                name="application_status_aef721_idx",
            ),
        ),
    ]
