# Generated by Django 5.1.15 on 2026-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_remove_expected_salary_from_job_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdocument",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Descriptive title for this document",
                max_length=200,
            ),
        ),
    ]
