# Generated by Django 5.1.15 on 2026-03-24 09:04

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_alter_applicationdocument_title"),
        ("authentication", "0027_userconsent_inherit_abstractbasemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SCREENING", "Screening"),
                            ("INTERVIEWING", "Interviewing"),
                            ("OFFERED", "Offered"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        help_text="Unique identifier for the category (e.g., 'HIRED', 'REJECTED')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Default display name in English", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this category represents",
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False,
                        help_text="If true, statuses in this category end the application process",
                    ),
                ),
                (
                    "is_positive_outcome",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this is a positive outcome (hired, accepted)",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Default order position for display"
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Category",
                "verbose_name_plural": "Status Categories",
                "ordering": ["position", "key"],
            },
        ),
        migrations.CreateModel(
            name="StatusTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this template",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Standard Hiring', 'Tech Recruiting')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this template's workflow"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this template is used for new companies",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If false, this template cannot be selected",
                    ),
                ),
                (
                    "statuses",
                    models.JSONField(
                        default=list,
                        help_text='\n            List of status definitions:\n            [\n                {\n                    "key": "APPLIED",\n                    "label": "Applied",\n                    "category": "APPLIED",\n                    "color": "#3B82F6",\n                    "position": 1,\n                    "show_in_kanban": true,\n                    "translations": {"ru": "Подано", "uz": "Topshirildi"}\n                }\n            ]\n        ',
                    ),
                ),
                (
                    "transitions",
                    models.JSONField(
                        default=list,
                        help_text='\n            List of transition rules:\n            [\n                {\n                    "from": "APPLIED",\n                    "to": "INTERVIEW_SCHEDULED",\n                    "recruiter": true,\n                    "candidate": false\n                }\n            ]\n        ',
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Template",
                "verbose_name_plural": "Status Templates",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this status",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key within the company (e.g., 'APPLIED', 'TECH_SCREEN')",
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name for this status", max_length=100
                    ),
                ),
                (
                    "translations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Translations: {'ru': 'Подано', 'uz': 'Topshirildi'}",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color for Kanban column (e.g., '#3B82F6')",
                        max_length=7,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order position in Kanban board (lower = first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="If false, status is archived and hidden from selection",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this status was created from the default template",
                    ),
                ),
                (
                    "show_in_kanban",
                    models.BooleanField(
                        default=True,
                        help_text="If false, status column is hidden from Kanban board",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns this status",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_statuses",
                        to="authentication.company",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Analytics category this status maps to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statuses",
                        to="applications.statuscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Status",
                "verbose_name_plural": "Application Statuses",
                "ordering": ["position", "key"],
            },
        ),
        migrations.CreateModel(
            name="StatusTransitionRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this rule",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recruiter_can_transition",
                    models.BooleanField(
                        default=False,
                        help_text="If true, recruiters can perform this transition",
                    ),
                ),
                (
                    "candidate_can_transition",
                    models.BooleanField(
                        default=False,
                        help_text="If true, candidates can perform this transition",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If false, this transition rule is disabled",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of when this transition applies",
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        help_text="Source status for this transition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="applications.applicationstatusmodel",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        help_text="Target status for this transition",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="applications.applicationstatusmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Transition Rule",
                "verbose_name_plural": "Status Transition Rules",
            },
        ),
        migrations.AddIndex(
            model_name="applicationstatusmodel",
            index=models.Index(
                fields=["company", "is_active"], name="application_company_251bd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationstatusmodel",
            index=models.Index(
                fields=["company", "position"], name="application_company_2d7401_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationstatusmodel",
            constraint=models.UniqueConstraint(
                fields=("key", "company"), name="unique_status_key_per_company"
            ),
        ),
        migrations.AddIndex(
            model_name="statustransitionrule",
            index=models.Index(
                fields=["from_status", "is_active"],
                name="application_from_st_b78bad_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="statustransitionrule",
            constraint=models.UniqueConstraint(
                fields=("from_status", "to_status"), name="unique_transition_rule"
            ),
        ),
    ]
