# Generated by Django 5.1.15 on 2026-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_remove_statustransitionrule"),
        ("authentication", "0033_customuser_preferred_language"),
        ("resumes", "0023_alter_resumelanguagecertificate_file_optional"),
        ("vacancies", "0021_add_vacancy_language"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "vacancy", "kanban_position"],
                name="application_status_938101_idx",
            ),
        ),
    ]
