# Generated by Django 5.1.15 on 2026-05-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0020_add_application_ai_evaluation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="applicationaievaluation",
            new_name="application_status_255a29_idx",
            old_name="application_status_idx",
        ),
        migrations.RenameIndex(
            model_name="applicationaievaluation",
            new_name="application_overall_e57479_idx",
            old_name="application_score_idx",
        ),
        migrations.AlterField(
            model_name="applicationaievaluation",
            name="application",
            field=models.OneToOneField(
                help_text="The job application this evaluation belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_evaluation",
                to="applications.jobapplication",
            ),
        ),
        migrations.AlterField(
            model_name="applicationaievaluation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="applicationaievaluation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                help_text="Current evaluation status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationaievaluation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="applicationdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("RESUME", "Resume"),
                    ("CERTIFICATE", "Certificate"),
                    ("PORTFOLIO", "Portfolio"),
                    ("REFERENCE", "Reference Letter"),
                    ("COVER_LETTER", "Cover Letter"),
                    ("TRANSCRIPT", "Academic Transcript"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
