# Generated by Django 5.1.15 on 2026-05-20 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0022_add_ai_evaluation_language_and_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
