# Generated by Django 5.2.13 on 2026-05-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0023_applicationdocument_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationdocument",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="applicationdocument",
            name="uploaded_at",
        ),
    ]
