# Generated by Django 5.1.15 on 2026-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0025_add_ai_failed_status_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationaievaluation",
            name="thinking_tokens",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of thinking/reasoning tokens used by the AI",
                null=True,
            ),
        ),
    ]
