# Generated by Django 5.1.15 on 2026-06-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0026_applicationaievaluation_thinking_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="is_demo",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If True, this application is demo/placeholder data shown to unapproved companies.",
            ),
        ),
    ]
