# Generated by Django 5.0.7 on 2025-10-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_uz", models.CharField(max_length=100, null=True, unique=True)),
                ("name_en", models.CharField(max_length=100, null=True, unique=True)),
                ("name_ru", models.CharField(max_length=100, null=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("description_uz", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Skill Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_uz", models.CharField(max_length=100, null=True, unique=True)),
                ("name_en", models.CharField(max_length=100, null=True, unique=True)),
                ("name_ru", models.CharField(max_length=100, null=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("description_uz", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ManyToManyField(blank=True, to="skills.skillcategory"),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="SkillSynonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synonym", models.CharField(max_length=100)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonyms",
                        to="skills.skill",
                    ),
                ),
            ],
        ),
    ]
