# Generated by Django 5.1.15 on 2026-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
