# Generated by Django 5.1.15 on 2026-06-06 11:13

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_skill_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("video", "Video"),
                            ("article", "Article"),
                            ("documentation", "Documentation"),
                        ],
                        default="course",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source platform, e.g. Coursera, YouTube",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Duration in hours",
                        max_digits=6,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="Content language", max_length=5
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Average rating (0-5)",
                        max_digits=3,
                    ),
                ),
                ("is_free", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Learning Material",
                "verbose_name_plural": "Learning Materials",
                "ordering": ["-rating", "title"],
                "indexes": [
                    models.Index(
                        fields=["material_type", "is_active"],
                        name="skills_lear_materia_8d0b41_idx",
                    ),
                    models.Index(
                        fields=["source"], name="skills_lear_source_492904_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillLearningMaterial",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relevance_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="AI-computed relevance score (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "is_top_match",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a top match for the skill",
                    ),
                ),
                (
                    "relevance_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated reason for the relevance ranking",
                    ),
                ),
                (
                    "vacancy_match_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Percentage of vacancies this material covers",
                        max_digits=5,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_materials",
                        to="skills.learningmaterial",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Learning Material",
                "verbose_name_plural": "Skill Learning Materials",
                "ordering": ["-relevance_score"],
                "indexes": [
                    models.Index(
                        fields=["skill", "-relevance_score"],
                        name="skills_skil_skill_i_a86f9b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("skill", "material"), name="unique_skill_material"
                    )
                ],
            },
        ),
    ]
