# Generated by Django 5.2.13 on 2026-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_learningmaterial_skilllearningmaterial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="learningmaterial",
            constraint=models.UniqueConstraint(
                fields=("url",), name="unique_learning_material_url"
            ),
        ),
    ]
