# Generated by Django 5.1.15 on 2026-07-20 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0005_learningmaterial_title_ru_uz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user (candidate or recruiter) who submitted this skill. Used to enforce per-user creation limits.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
