# Generated by Django 5.1.15 on 2026-05-31 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vacancies", "0022_add_minimum_ai_score_to_vacancy"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slide_type",
                    models.CharField(
                        choices=[
                            ("VACANCY", "Vacancy"),
                            ("NEWS", "News"),
                            ("AD", "Advertisement"),
                        ],
                        default="NEWS",
                        max_length=10,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Position in the carousel among manual slides (lower = first).",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="How many seconds this slide stays visible before auto-advancing.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, slide is hidden before this datetime.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, slide is hidden after this datetime.",
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="banner_slides/"
                    ),
                ),
                ("cta_label", models.CharField(blank=True, default="", max_length=80)),
                ("cta_url", models.CharField(blank=True, default="", max_length=500)),
                (
                    "brand_color_from",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex e.g. #F8EDD9",
                        max_length=7,
                    ),
                ),
                (
                    "brand_color_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex e.g. #FCE8DA",
                        max_length=7,
                    ),
                ),
                (
                    "brand_accent_color",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                (
                    "brand_text_color",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                (
                    "brand_border_color",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vacancy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when slide_type=VACANCY.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banner_slides",
                        to="vacancies.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Slide",
                "verbose_name_plural": "Banner Slides",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
