# Generated by Django 5.1.15 on 2026-05-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerslide",
            name="image_desktop",
            field=models.ImageField(
                blank=True,
                help_text="Full-cover background image for desktop (≥768\u202fpx). NEWS/AD only.",
                null=True,
                upload_to="banner_slides/desktop/",
            ),
        ),
        migrations.AddField(
            model_name="bannerslide",
            name="image_mobile",
            field=models.ImageField(
                blank=True,
                help_text="Full-cover background image for mobile (<768\u202fpx). Falls back to desktop image if not set.",
                null=True,
                upload_to="banner_slides/mobile/",
            ),
        ),
        migrations.AlterField(
            model_name="bannerslide",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Inline content image shown inside the slide body.",
                null=True,
                upload_to="banner_slides/",
            ),
        ),
    ]
