from django.test import TestCase

from apps.authentication.models import Candidate
from apps.authentication.transitions import CREATE_RESUME
from apps.resumes.models import Resume
from apps.resumes.tasks import _save_generated_resume


class SaveGeneratedResumeTests(TestCase):
    def test_marks_create_resume_step_when_ai_resume_is_saved(self):
        candidate = Candidate.objects.create_user(
            email="ai-resume@test.com",
            password="pass123",
            is_candidate=True,
            onboarding_progress={},
        )

        resume = _save_generated_resume(
            str(candidate.id),
            {
                "resume": {
                    "title": "AI Resume",
                    "description": "Generated by AI",
                    "position": "Backend Developer",
                }
            },
        )

        candidate.refresh_from_db()
        self.assertEqual(resume.created_by_type, Resume.CreatedByType.AI_GENERATED)
        self.assertFalse(resume.is_reviewed)
        self.assertIn(CREATE_RESUME, candidate.onboarding_progress)
        
    def test_uses_default_work_status_when_ai_payload_work_status_is_none(self):
            candidate = Candidate.objects.create_user(
                email="ai-resume-null-work-status@test.com",
                password="pass123",
                is_candidate=True,
                onboarding_progress={},
            )

            resume = _save_generated_resume(
                str(candidate.id),
                {
                    "resume": {
                        "title": "AI Resume",
                        "description": "Generated by AI",
                        "position": "Backend Developer",
                        "work_status": None,
                    }
                },
            )

            self.assertEqual(resume.work_status, "ACTIVELY_LOOKING")