# Generated by Django 5.0.7 on 2025-10-14 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="recruiter_photos/"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Middle", "Middle"),
                            ("Senior", "Senior"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.recruiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recruiter Profile",
                "verbose_name_plural": "Recruiter Profiles",
                "indexes": [
                    models.Index(
                        fields=["recruiter"], name="authenticat_recruit_99ae00_idx"
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="authenticat_first_n_4166ca_idx",
                    ),
                    models.Index(fields=["level"], name="authenticat_level_a9b48b_idx"),
                ],
            },
        ),
    ]
