# Generated by Django 5.0.7 on 2025-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_recruiterprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterprofile",
            name="level",
            field=models.CharField(
                choices=[
                    ("Recruiter", "Recruiter"),
                    ("Manager", "Manager"),
                    ("Admin", "Admin"),
                ],
                max_length=255,
            ),
        ),
    ]
