# Generated by Django 5.0.7 on 2025-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_recruiterprofile_level"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recruiterprofile",
            name="authenticat_first_n_4166ca_idx",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="full_name",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="recruiterprofile",
            index=models.Index(
                fields=["full_name"], name="authenticat_full_na_06f026_idx"
            ),
        ),
    ]
