# Generated by Django 5.0.7 on 2025-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_remove_recruiterprofile_authenticat_first_n_4166ca_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
