# Generated by Django 5.0.7 on 2025-10-15 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_company_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="company_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "zip"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
