# Generated by Django 5.0.7 on 2025-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_company_file_company_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterprofile",
            name="level",
            field=models.CharField(
                choices=[
                    ("Recruiter", "Recruiter"),
                    ("Manager", "Manager"),
                    ("Admin", "Admin"),
                ],
                default="Recruiter",
                max_length=20,
            ),
        ),
    ]
