# Generated by Django 5.0.7 on 2025-10-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_recruiterprofile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiter",
            name="is_waiting_approval",
            field=models.BooleanField(default=False),
        ),
    ]
