# Generated by Django 5.0.7 on 2025-10-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_recruiter_is_waiting_approval"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecruiterProfile",
        ),
    ]
