# Generated by Django 5.0.7 on 2025-11-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_delete_recruiterprofile"),
        ("edupartners", "0002_alter_edupartner_id_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="edupartner",
            field=models.ForeignKey(
                blank=True,
                help_text="The educational institution the candidate is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="edupartners.edupartner",
                verbose_name="Educational Partner",
            ),
        ),
    ]
