# Generated by Django 5.0.7 on 2025-11-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_candidate_edupartner"),
        ("edupartners", "0003_alter_edupartner_id_alter_faculty_id_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                help_text="The faculty the candidate is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="edupartners.faculty",
                verbose_name="Faculty",
            ),
        ),
    ]
