# Generated by Django 5.0.7 on 2025-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_candidate_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Candidate's date of birth for age calculation in analytics",
                null=True,
            ),
        ),
    ]
