# Generated by Django 5.0.7 on 2025-11-22 14:04

import utils.fields.uuid7_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=utils.fields.uuid7_field.UUIDField(
                default=utils.fields.uuid7_field.uuidv7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
