# Generated by Django 5.0.7 on 2025-11-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_candidate_date_of_birth"),
        ("authentication", "0013_alter_company_id"),
    ]

    operations = []
