# Generated by Django 5.0.7 on 2025-11-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_merge_20251124_2349"),
        ("authentication", "0014_merge_20251125_2235"),
    ]

    operations = []
