# Generated by Django 5.0.7 on 2025-12-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_merge_20251129_1300"),
        ("domain", "0002_hrcreatedprofession"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                help_text="Company specialization domain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="domain.domain",
            ),
        ),
    ]
