# Generated by Django 5.0.7 on 2025-12-16 10:56

from django.db import migrations


def migrate_company_types_to_domains(apps, schema_editor):
    """
    Migrate existing company types to Domain model and link companies to domains.
    """
    Company = apps.get_model('authentication', 'Company')
    Domain = apps.get_model('domain', 'Domain')
    
    # Get all unique company types
    company_types = set(
        Company.objects.exclude(type__isnull=True)
        .exclude(type="")
        .values_list('type', flat=True)
        .distinct()
    )
    
    # Create Domain records for each unique type
    domain_mapping = {}
    for company_type in company_types:
        domain, created = Domain.objects.get_or_create(
            name=company_type,
            defaults={
                'description': f'Companies in {company_type} sector'
            }
        )
        domain_mapping[company_type] = domain
    
    # Link companies to their corresponding domains
    for company in Company.objects.exclude(type__isnull=True).exclude(type=""):
        if company.type in domain_mapping:
            company.domain = domain_mapping[company.type]
            company.save(update_fields=['domain'])


def reverse_migrate_domains_to_company_types(apps, schema_editor):
    """
    Reverse migration: set company.type based on company.domain.name
    """
    Company = apps.get_model('authentication', 'Company')
    
    for company in Company.objects.exclude(domain__isnull=True):
        company.type = company.domain.name
        company.save(update_fields=['type'])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_add_domain_field_to_company"),
        ("domain", "0002_hrcreatedprofession"),
    ]

    operations = [
        migrations.RunPython(
            migrate_company_types_to_domains,
            reverse_migrate_domains_to_company_types
        ),
    ]
