# Generated by Django 5.0.7 on 2025-12-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_migrate_company_types_to_domains"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="type",
        ),
    ]
