# Generated by Django 5.0.7 on 2026-02-02 15:53

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_remove_company_type_field"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of Service"),
                            ("privacy_policy", "Privacy Policy"),
                            ("data_processing", "Data Processing Agreement"),
                            ("company_terms", "Company Terms and Conditions"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version of the policy agreed to (e.g., '1.0', '2.0')",
                        max_length=20,
                    ),
                ),
                ("agreed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address from which consent was given"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser/device information"
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp if consent was withdrawn",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Record",
                "verbose_name_plural": "Consent Records",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="authenticat_content_001ea2_idx",
                    ),
                    models.Index(
                        fields=["consent_type"], name="authenticat_consent_968bfc_idx"
                    ),
                    models.Index(
                        fields=["agreed_at"], name="authenticat_agreed__7ca308_idx"
                    ),
                ],
                "unique_together": {
                    ("content_type", "object_id", "consent_type", "version")
                },
            },
        ),
    ]
