# Generated by Django 5.0.7 on 2026-02-03 16:40

import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_userconsent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentConfiguration",
            fields=[
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("recruiter", "Recruiter"),
                            ("company", "Company"),
                        ],
                        help_text="Type of user/entity this consent requirement applies to",
                        max_length=20,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of Service"),
                            ("privacy_policy", "Privacy Policy"),
                            ("data_processing", "Data Processing Agreement"),
                            ("company_terms", "Company Terms and Conditions"),
                        ],
                        help_text="Type of consent required",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Current version of this policy (e.g., '1.0', '2.1')",
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this consent is mandatory for registration",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label for frontend display",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description explaining what this consent covers",
                    ),
                ),
                (
                    "policy_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the policy document (e.g., /terms-of-service)",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which to display this consent (lower = first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this consent requirement is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent Configuration",
                "verbose_name_plural": "Consent Configurations",
                "ordering": ["entity_type", "display_order"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "is_active"],
                        name="authenticat_entity__ef06b4_idx",
                    ),
                    models.Index(
                        fields=["consent_type"], name="authenticat_consent_609def_idx"
                    ),
                ],
                "unique_together": {("entity_type", "consent_type")},
            },
        ),
    ]
