# Generated by Django 5.0.7 on 2026-02-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_consentconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consentconfiguration",
            options={
                "verbose_name": "Consent Configuration",
                "verbose_name_plural": "Consent Configurations",
            },
        ),
        migrations.RemoveIndex(
            model_name="consentconfiguration",
            name="authenticat_entity__ef06b4_idx",
        ),
        migrations.RemoveIndex(
            model_name="consentconfiguration",
            name="authenticat_consent_609def_idx",
        ),
        migrations.AlterUniqueTogether(
            name="consentconfiguration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="consentconfiguration",
            name="description_en",
            field=models.TextField(blank=True, help_text="Description in English"),
        ),
        migrations.AddField(
            model_name="consentconfiguration",
            name="description_ru",
            field=models.TextField(blank=True, help_text="Description in Russian"),
        ),
        migrations.AddField(
            model_name="consentconfiguration",
            name="description_uz",
            field=models.TextField(blank=True, help_text="Description in Uzbek"),
        ),
        migrations.AddField(
            model_name="consentconfiguration",
            name="name",
            field=models.CharField(
                blank=True, help_text="Display name for this consent", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="consentconfiguration",
            name="name_en",
            field=models.CharField(
                blank=True, help_text="Display name in English", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="consentconfiguration",
            name="name_ru",
            field=models.CharField(
                blank=True, help_text="Display name in Russian", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="consentconfiguration",
            name="name_uz",
            field=models.CharField(
                blank=True, help_text="Display name in Uzbek", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="userconsent",
            name="consent_config",
            field=models.ForeignKey(
                blank=True,
                help_text="The configuration this consent was given under",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consent_records",
                to="authentication.consentconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="consentconfiguration",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("terms_of_service", "Terms of Service"),
                    ("privacy_policy", "Privacy Policy"),
                    ("data_processing", "Data Processing Agreement"),
                    ("company_terms", "Company Terms and Conditions"),
                ],
                help_text="Type of consent (e.g., terms_of_service, privacy_policy)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="consentconfiguration",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of what this consent covers"
            ),
        ),
        migrations.AlterField(
            model_name="consentconfiguration",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate"),
                    ("recruiter", "Recruiter"),
                    ("company", "Company"),
                ],
                help_text="Which type of user this consent applies to",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consentconfiguration",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this consent configuration is currently active",
            ),
        ),
        migrations.AlterField(
            model_name="consentconfiguration",
            name="version",
            field=models.CharField(
                help_text="Version of this consent (e.g., '1.0', '2.0')", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="consent_type",
            field=models.CharField(
                help_text="Type of consent (e.g., 'terms_of_service', 'privacy_policy')",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="consentconfiguration",
            index=models.Index(
                fields=["consent_type", "entity_type", "is_active"],
                name="authenticat_consent_94533c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentconfiguration",
            index=models.Index(
                fields=["is_active"], name="authenticat_is_acti_bf5e5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="consentconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("consent_type", "entity_type"),
                name="unique_active_consent_config",
            ),
        ),
        migrations.RemoveField(
            model_name="consentconfiguration",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="consentconfiguration",
            name="is_required",
        ),
        migrations.RemoveField(
            model_name="consentconfiguration",
            name="label",
        ),
        migrations.RemoveField(
            model_name="consentconfiguration",
            name="policy_url",
        ),
    ]
