# Generated by Django 5.0.7 on 2026-02-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0021_alter_consentconfiguration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="User's timezone (e.g., 'Asia/Tashkent')",
                max_length=50,
                null=True,
            ),
        ),
    ]
