# Generated by Django 5.1.15 on 2026-02-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0022_customuser_timezone"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customuser",
            name="authenticat_email_486e08_idx",
        ),
    ]
