# Generated by Django 5.1.15 on 2026-02-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_remove_customuser_authenticat_email_486e08_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_vault_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the candidate's identity has been verified through Vault",
            ),
        ),
    ]
