# Generated by Django 5.1.15 on 2026-03-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_candidate_is_vault_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="user_agent",
            field=models.TextField(
                blank=True, default="", help_text="Browser/device information"
            ),
        ),
    ]
