# Generated by Django 5.1.15 on 2026-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_userconsent_inherit_abstractbasemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="tin",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
