# Generated by Django 5.1.15 on 2026-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_alter_company_tin"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="onboarding_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
