# Generated by Django 5.1.15 on 2026-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_candidate_onboarding_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="onboarding_progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tracks completed onboarding steps as {step_code: ISO timestamp}",
            ),
        ),
    ]
