# Generated by Django 5.1.15 on 2026-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_candidate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("uz", "Uzbek"), ("ru", "Russian"), ("en", "English")],
                default="uz",
                help_text="User's preferred language for notifications and UI.",
                max_length=5,
            ),
        ),
    ]
