# Generated by Django 5.2.13 on 2026-06-06 11:19

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0033_customuser_preferred_language"),
        ("resumes", "0025_resume_is_reviewed"),
        ("skills", "0003_learningmaterial_skilllearningmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAnalytics",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Target role for analytics, e.g. 'Product Designer'",
                        max_length=255,
                    ),
                ),
                (
                    "market_match_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Percentage match against market requirements",
                        max_digits=5,
                    ),
                ),
                (
                    "market_match_insight",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated insight text explaining the match percentage",
                    ),
                ),
                (
                    "track_progress_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Overall roadmap completion percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "verified_skills_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of skills verified via tests"
                    ),
                ),
                (
                    "total_roadmap_skills",
                    models.PositiveIntegerField(
                        default=0, help_text="Total skills in the roadmap"
                    ),
                ),
                (
                    "last_computed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When analytics were last recomputed",
                        null=True,
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="authentication.customuser",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Analytics",
                "verbose_name_plural": "Student Analytics",
            },
        ),
        migrations.CreateModel(
            name="SkillRoadmap",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "ai_model",
                    models.CharField(
                        default="default",
                        help_text="AI model used to generate this roadmap",
                        max_length=30,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the roadmap was generated"
                    ),
                ),
                (
                    "analytics",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap",
                        to="student_analytics.studentanalytics",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Roadmap",
                "verbose_name_plural": "Skill Roadmaps",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position in the roadmap sequence"
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        default="INTERMEDIATE",
                        help_text="Target proficiency level",
                        max_length=20,
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        default="UNDEFINED",
                        help_text="Candidate's current proficiency level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("verified", "Verified"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this skill is critical for the target role",
                    ),
                ),
                (
                    "impact_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="AI-estimated impact on hire chances",
                        max_digits=5,
                    ),
                ),
                (
                    "vacancy_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of vacancies requiring this skill"
                    ),
                ),
                (
                    "salary_impact_percentage",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Estimated salary impact percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "learning_time_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="AI-estimated hours to learn this skill"
                    ),
                ),
                (
                    "learning_time_weeks",
                    models.PositiveIntegerField(
                        default=0, help_text="AI-estimated weeks to learn this skill"
                    ),
                ),
                (
                    "context_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated context message for the skill detail page",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roadmap_items",
                        to="skills.skill",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="student_analytics.skillroadmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap Item",
                "verbose_name_plural": "Roadmap Items",
                "ordering": ["roadmap", "order"],
                "indexes": [
                    models.Index(
                        fields=["roadmap", "order"],
                        name="student_ana_roadmap_879c3a_idx",
                    ),
                    models.Index(
                        fields=["roadmap", "status"],
                        name="student_ana_roadmap_f068bb_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roadmap", "skill"), name="unique_roadmap_skill"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="studentanalytics",
            index=models.Index(
                fields=["candidate"], name="student_ana_candida_1156e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentanalytics",
            index=models.Index(
                fields=["resume"], name="student_ana_resume__8fdfe1_idx"
            ),
        ),
    ]
