# Generated by Django 5.2.13 on 2026-06-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentanalytics",
            name="skills_to_improve",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Skills the candidate needs to learn or improve",
            ),
        ),
        migrations.AddField(
            model_name="studentanalytics",
            name="strong_skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Skills the candidate already has that match market demand",
            ),
        ),
    ]
