# Generated by Django 5.1.15 on 2026-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_analytics", "0002_studentanalytics_skills_to_improve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillroadmap",
            name="input_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="AI input tokens used for roadmap generation"
            ),
        ),
        migrations.AddField(
            model_name="skillroadmap",
            name="output_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="AI output tokens used for roadmap generation"
            ),
        ),
        migrations.AddField(
            model_name="studentanalytics",
            name="input_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="AI input tokens used for market match insight"
            ),
        ),
        migrations.AddField(
            model_name="studentanalytics",
            name="output_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="AI output tokens used for market match insight"
            ),
        ),
    ]
