# Generated by Django 5.1.15 on 2026-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_analytics", "0003_add_input_output_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillroadmap",
            name="thinking_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="AI thinking/reasoning tokens used for roadmap generation",
            ),
        ),
        migrations.AddField(
            model_name="studentanalytics",
            name="thinking_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="AI thinking/reasoning tokens used for market match insight",
            ),
        ),
    ]
