# Generated by Django 5.1.15 on 2026-06-26 10:17

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0027_jobapplication_is_demo"),
        ("skills", "0005_learningmaterial_title_ru_uz"),
        ("student_analytics", "0004_skillroadmap_thinking_tokens_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancySkillRoadmap",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rejection_summary",
                    models.JSONField(
                        default=dict,
                        help_text="AI-generated rejection summary in uz/ru/en",
                    ),
                ),
                ("ai_model", models.CharField(default="groq", max_length=30)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("thinking_tokens", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_skill_roadmap",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy Skill Roadmap",
                "verbose_name_plural": "Vacancy Skill Roadmaps",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="VacancyRoadmapItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "target_level",
                    models.CharField(default="INTERMEDIATE", max_length=20),
                ),
                ("current_level", models.CharField(default="UNDEFINED", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("verified", "Verified"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("is_critical", models.BooleanField(default=False)),
                (
                    "impact_percentage",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("context_message", models.TextField(blank=True, default="")),
                ("learning_time_hours", models.PositiveIntegerField(default=0)),
                ("learning_time_weeks", models.PositiveIntegerField(default=0)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancy_roadmap_items",
                        to="skills.skill",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="student_analytics.vacancyskillroadmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy Roadmap Item",
                "verbose_name_plural": "Vacancy Roadmap Items",
                "ordering": ["roadmap", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roadmap", "skill"), name="unique_vacancy_roadmap_skill"
                    )
                ],
            },
        ),
    ]
