# Generated by Django 5.0.7 on 2025-12-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("application_accepted", "Application Accepted"),
                    ("application_rejected", "Application Rejected"),
                    ("application_offered", "Application Offered"),
                    ("new_job_match", "New Job Match"),
                    ("platform_announcement", "Platform Announcement"),
                    ("profile_update_reminder", "Profile Update Reminder"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_reminder", "Interview Reminder"),
                ],
                db_index=True,
                default="platform_announcement",
                max_length=50,
            ),
        ),
    ]
