# Generated by Django 5.1.15 on 2026-04-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("application_applied", "Application Applied"),
                    ("application_status_updated", "Application Status Updated"),
                    ("application_accepted", "Application Accepted"),
                    ("application_rejected", "Application Rejected"),
                    ("application_offered", "Application Offered"),
                    ("new_job_match", "New Job Match"),
                    ("platform_announcement", "Platform Announcement"),
                    ("profile_update_reminder", "Profile Update Reminder"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_reminder", "Interview Reminder"),
                ],
                db_index=True,
                default="platform_announcement",
                max_length=50,
            ),
        ),
    ]
