# Generated by Django 5.2.13 on 2026-06-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False  # CONCURRENTLY index creation cannot run inside a transaction

    dependencies = [
        ("notifications", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- Composite index for the most common notification listing query:
                --   SELECT ... FROM notification_recipient
                --   WHERE user_id = ? AND is_read = ?
                --   ORDER BY notification_id DESC (proxy for created_at order)
                -- This enables index-only scans for the filter + efficient join.
                CREATE INDEX CONCURRENTLY IF NOT EXISTS
                    idx_nr_user_notification
                ON notifications_notificationrecipient (user_id, notification_id);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS idx_nr_user_notification;
            """,
        ),
        migrations.RunSQL(
            sql="""
                -- Partial index: only rows where is_read=FALSE.
                -- Dramatically speeds up unread COUNT and bulk-mark-as-read.
                CREATE INDEX CONCURRENTLY IF NOT EXISTS
                    idx_nr_user_unread
                ON notifications_notificationrecipient (user_id)
                WHERE is_read = FALSE;
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS idx_nr_user_unread;
            """,
        ),
        migrations.RunSQL(
            sql="""
                -- Covering index for the full listing path:
                --   WHERE user_id = ? [AND is_read = ?]
                --   ORDER BY notification_id (→ join to notification.created_at)
                CREATE INDEX CONCURRENTLY IF NOT EXISTS
                    idx_nr_user_isread_notification
                ON notifications_notificationrecipient (user_id, is_read, notification_id);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS idx_nr_user_isread_notification;
            """,
        ),
    ]
