# Generated by Django 5.0.7 on 2026-01-28 12:04

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0010_alter_jobapplication_status"),
        ("authentication", "0018_remove_company_type_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this conversation",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_read_by_recruiter",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recruiter has read the messages",
                    ),
                ),
                (
                    "is_read_by_candidate",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the candidate has read the messages",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        help_text="The job application this conversation is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        help_text="The candidate participating in this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="authentication.candidate",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="The recruiter participating in this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="authentication.recruiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this message",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("CANDIDATE", "Candidate"),
                            ("RECRUITER", "Recruiter"),
                            ("SYSTEM", "System"),
                        ],
                        help_text="Type of the sender",
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("COVER_LETTER", "Cover Letter"),
                            ("TEXT", "Text Message"),
                            ("SYSTEM", "System Message"),
                        ],
                        default="COVER_LETTER",
                        help_text="Type of the message",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="The message content")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been read by the recipient",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="The conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["candidate", "recruiter"], name="conversatio_candida_512697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["recruiter", "-created_at"],
                name="conversatio_recruit_33a3d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["candidate", "-created_at"],
                name="conversatio_candida_a5276a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="conversatio_convers_4b968d_idx",
            ),
        ),
    ]
