# Generated by Django 5.0.7 on 2026-01-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_alter_jobapplication_status"),
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="application",
            field=models.OneToOneField(
                blank=True,
                help_text="The job application this conversation is about (null for headhunting)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="applications.jobapplication",
            ),
        ),
    ]
