# Generated by Django 5.0.7 on 2026-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_alter_jobapplication_status"),
        ("authentication", "0018_remove_company_type_field"),
        ("conversations", "0002_alter_conversation_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional structured data for special message types. For STATUS_CHANGE: {old_status, new_status, old_status_display, new_status_display, recruiter_note}. For DOCUMENT: {title, file_url, file_size, document_type}.",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("COVER_LETTER", "Cover Letter"),
                    ("TEXT", "Text Message"),
                    ("SYSTEM", "System Message"),
                    ("STATUS_CHANGE", "Status Change"),
                    ("DOCUMENT", "Document"),
                ],
                default="COVER_LETTER",
                help_text="Type of the message",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("application__isnull", False)),
                fields=("candidate", "recruiter", "application"),
                name="unique_application_conversation",
            ),
        ),
    ]
