# Generated by Django 5.0.7 on 2026-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_alter_jobapplication_status"),
        ("authentication", "0018_remove_company_type_field"),
        ("conversations", "0003_message_metadata_alter_message_message_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_read", "sender_type"],
                name="message_unread_sender_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("application__isnull", True)),
                fields=("candidate", "recruiter"),
                name="unique_headhunting_conversation",
            ),
        ),
    ]
