# Generated by Django 5.0.7 on 2026-02-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0004_add_headhunting_constraint_and_message_index"),
        ("vacancies", "0012_vacancyview_viewed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                help_text="The vacancy this headhunting invitation is for (null for application conversations)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headhunting_conversations",
                to="vacancies.vacancy",
            ),
        ),
    ]
