# Generated by Django 5.0.7 on 2026-02-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_alter_jobapplication_status"),
        ("authentication", "0019_userconsent"),
        ("conversations", "0005_add_vacancy_to_conversation"),
        ("vacancies", "0012_vacancyview_viewed_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("application__isnull", True), ("vacancy__isnull", False)),
                    models.Q(("application__isnull", True), ("vacancy__isnull", True)),
                    models.Q(("application__isnull", False), ("vacancy__isnull", True)),
                    _connector="OR",
                ),
                name="check_application_vacancy_exclusivity",
                violation_error_message="Application conversations cannot have a direct vacancy. Use application.vacancy instead.",
            ),
        ),
    ]
