# Generated by Django 5.0.7 on 2026-02-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0006_conversation_check_application_vacancy_exclusivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("COVER_LETTER", "Cover Letter"),
                    ("TEXT", "Text Message"),
                    ("SYSTEM", "System Message"),
                    ("STATUS_CHANGE", "Status Change"),
                    ("DOCUMENT", "Document"),
                    ("HUNTING_INVITATION", "Headhunting Invitation"),
                ],
                default="COVER_LETTER",
                help_text="Type of the message",
                max_length=20,
            ),
        ),
    ]
