# Generated by Django 5.1.15 on 2026-02-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0007_alter_message_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional title for the message (e.g., recruiter note title for status changes)",
                max_length=255,
                null=True,
            ),
        ),
    ]
