# Generated by Django 5.1.15 on 2026-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_remove_statustransitionrule"),
        ("authentication", "0033_customuser_preferred_language"),
        ("conversations", "0008_add_title_to_message"),
        ("vacancies", "0021_add_vacancy_language"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["candidate", "recruiter", "vacancy"],
                name="conv_headhunting_lookup_idx",
            ),
        ),
    ]
