# Generated by Django 5.2.13 on 2026-05-18 06:12

import django.db.models.deletion
import utils.fields.uuid7_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0022_add_ai_evaluation_language_and_tokens"),
        ("authentication", "0033_customuser_preferred_language"),
        ("conversations", "0009_add_headhunting_lookup_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDiscussion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    utils.fields.uuid7_field.UUIDField(
                        default=utils.fields.uuid7_field.uuidv7,
                        editable=False,
                        help_text="Unique identifier for this discussion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The discussion message content"),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this discussion has been edited",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="The job application this discussion is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_discussions",
                        to="applications.jobapplication",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="The recruiter who wrote this discussion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_discussions",
                        to="authentication.recruiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Discussion",
                "verbose_name_plural": "Application Discussions",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "created_at"],
                        name="discussion_app_created_idx",
                    )
                ],
            },
        ),
    ]
