# Generated by Django 5.1.15 on 2026-05-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0010_applicationdiscussion"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationdiscussion",
            name="status_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Application status key at the time this discussion was created",
                max_length=50,
                null=True,
            ),
        ),
    ]
